//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IN20200
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IN20200Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IN20200Entities object using the connection string found in the 'IN20200Entities' section of the application configuration file.
        /// </summary>
        public IN20200Entities() : base("name=IN20200Entities", "IN20200Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IN20200Entities object.
        /// </summary>
        public IN20200Entities(string connectionString) : base(connectionString, "IN20200Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IN20200Entities object.
        /// </summary>
        public IN20200Entities(EntityConnection connection) : base(connection, "IN20200Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IN_ProdClassCpny> IN_ProdClassCpny
        {
            get
            {
                if ((_IN_ProdClassCpny == null))
                {
                    _IN_ProdClassCpny = base.CreateObjectSet<IN_ProdClassCpny>("IN_ProdClassCpny");
                }
                return _IN_ProdClassCpny;
            }
        }
        private ObjectSet<IN_ProdClassCpny> _IN_ProdClassCpny;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IN_ProductClass> IN_ProductClass
        {
            get
            {
                if ((_IN_ProductClass == null))
                {
                    _IN_ProductClass = base.CreateObjectSet<IN_ProductClass>("IN_ProductClass");
                }
                return _IN_ProductClass;
            }
        }
        private ObjectSet<IN_ProductClass> _IN_ProductClass;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IN_UnitConversion> IN_UnitConversion
        {
            get
            {
                if ((_IN_UnitConversion == null))
                {
                    _IN_UnitConversion = base.CreateObjectSet<IN_UnitConversion>("IN_UnitConversion");
                }
                return _IN_UnitConversion;
            }
        }
        private ObjectSet<IN_UnitConversion> _IN_UnitConversion;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IN_ProdClassCpny EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIN_ProdClassCpny(IN_ProdClassCpny iN_ProdClassCpny)
        {
            base.AddObject("IN_ProdClassCpny", iN_ProdClassCpny);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IN_ProductClass EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIN_ProductClass(IN_ProductClass iN_ProductClass)
        {
            base.AddObject("IN_ProductClass", iN_ProductClass);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IN_UnitConversion EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIN_UnitConversion(IN_UnitConversion iN_UnitConversion)
        {
            base.AddObject("IN_UnitConversion", iN_UnitConversion);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="classID">No Metadata Documentation available.</param>
        public ObjectResult<IN20200_pgLoadgetCompany_Result> IN20200_pgLoadgetCompany(global::System.String classID)
        {
            ObjectParameter classIDParameter;
            if (classID != null)
            {
                classIDParameter = new ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new ObjectParameter("ClassID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<IN20200_pgLoadgetCompany_Result>("IN20200_pgLoadgetCompany", classIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="classID">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Boolean>> IN20200_ppCheckClassID(global::System.String classID)
        {
            ObjectParameter classIDParameter;
            if (classID != null)
            {
                classIDParameter = new ObjectParameter("ClassID", classID);
            }
            else
            {
                classIDParameter = new ObjectParameter("ClassID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Boolean>>("IN20200_ppCheckClassID", classIDParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN20200Model", Name="IN_ProdClassCpny")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IN_ProdClassCpny : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN_ProdClassCpny object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        /// <param name="cpnyID">Initial value of the CpnyID property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static IN_ProdClassCpny CreateIN_ProdClassCpny(global::System.String classID, global::System.String cpnyID, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp)
        {
            IN_ProdClassCpny iN_ProdClassCpny = new IN_ProdClassCpny();
            iN_ProdClassCpny.ClassID = classID;
            iN_ProdClassCpny.CpnyID = cpnyID;
            iN_ProdClassCpny.Crtd_DateTime = crtd_DateTime;
            iN_ProdClassCpny.Crtd_Prog = crtd_Prog;
            iN_ProdClassCpny.Crtd_User = crtd_User;
            iN_ProdClassCpny.LUpd_DateTime = lUpd_DateTime;
            iN_ProdClassCpny.LUpd_Prog = lUpd_Prog;
            iN_ProdClassCpny.LUpd_User = lUpd_User;
            iN_ProdClassCpny.tstamp = tstamp;
            return iN_ProdClassCpny;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CpnyID
        {
            get
            {
                return _CpnyID;
            }
            set
            {
                if (_CpnyID != value)
                {
                    OnCpnyIDChanging(value);
                    ReportPropertyChanging("CpnyID");
                    _CpnyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CpnyID");
                    OnCpnyIDChanged();
                }
            }
        }
        private global::System.String _CpnyID;
        partial void OnCpnyIDChanging(global::System.String value);
        partial void OnCpnyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN20200Model", Name="IN_ProductClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IN_ProductClass : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN_ProductClass object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        /// <param name="dfltLotSerNumLen">Initial value of the DfltLotSerNumLen property.</param>
        /// <param name="dfltLotSerShelfLife">Initial value of the DfltLotSerShelfLife property.</param>
        /// <param name="dfltStkItem">Initial value of the DfltStkItem property.</param>
        /// <param name="dfltWarrantyDays">Initial value of the DfltWarrantyDays property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static IN_ProductClass CreateIN_ProductClass(global::System.String classID, global::System.Int16 dfltLotSerNumLen, global::System.Int16 dfltLotSerShelfLife, global::System.Int16 dfltStkItem, global::System.Int16 dfltWarrantyDays, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp)
        {
            IN_ProductClass iN_ProductClass = new IN_ProductClass();
            iN_ProductClass.ClassID = classID;
            iN_ProductClass.DfltLotSerNumLen = dfltLotSerNumLen;
            iN_ProductClass.DfltLotSerShelfLife = dfltLotSerShelfLife;
            iN_ProductClass.DfltStkItem = dfltStkItem;
            iN_ProductClass.DfltWarrantyDays = dfltWarrantyDays;
            iN_ProductClass.Crtd_DateTime = crtd_DateTime;
            iN_ProductClass.Crtd_Prog = crtd_Prog;
            iN_ProductClass.Crtd_User = crtd_User;
            iN_ProductClass.LUpd_DateTime = lUpd_DateTime;
            iN_ProductClass.LUpd_Prog = lUpd_Prog;
            iN_ProductClass.LUpd_User = lUpd_User;
            iN_ProductClass.tstamp = tstamp;
            return iN_ProductClass;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descr
        {
            get
            {
                return _Descr;
            }
            set
            {
                OnDescrChanging(value);
                ReportPropertyChanging("Descr");
                _Descr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descr");
                OnDescrChanged();
            }
        }
        private global::System.String _Descr;
        partial void OnDescrChanging(global::System.String value);
        partial void OnDescrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltInvtType
        {
            get
            {
                return _DfltInvtType;
            }
            set
            {
                OnDfltInvtTypeChanging(value);
                ReportPropertyChanging("DfltInvtType");
                _DfltInvtType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltInvtType");
                OnDfltInvtTypeChanged();
            }
        }
        private global::System.String _DfltInvtType;
        partial void OnDfltInvtTypeChanging(global::System.String value);
        partial void OnDfltInvtTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltSource
        {
            get
            {
                return _DfltSource;
            }
            set
            {
                OnDfltSourceChanging(value);
                ReportPropertyChanging("DfltSource");
                _DfltSource = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltSource");
                OnDfltSourceChanged();
            }
        }
        private global::System.String _DfltSource;
        partial void OnDfltSourceChanging(global::System.String value);
        partial void OnDfltSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltValMthd
        {
            get
            {
                return _DfltValMthd;
            }
            set
            {
                OnDfltValMthdChanging(value);
                ReportPropertyChanging("DfltValMthd");
                _DfltValMthd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltValMthd");
                OnDfltValMthdChanged();
            }
        }
        private global::System.String _DfltValMthd;
        partial void OnDfltValMthdChanging(global::System.String value);
        partial void OnDfltValMthdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltLotSerTrack
        {
            get
            {
                return _DfltLotSerTrack;
            }
            set
            {
                OnDfltLotSerTrackChanging(value);
                ReportPropertyChanging("DfltLotSerTrack");
                _DfltLotSerTrack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltLotSerTrack");
                OnDfltLotSerTrackChanged();
            }
        }
        private global::System.String _DfltLotSerTrack;
        partial void OnDfltLotSerTrackChanging(global::System.String value);
        partial void OnDfltLotSerTrackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Buyer
        {
            get
            {
                return _Buyer;
            }
            set
            {
                OnBuyerChanging(value);
                ReportPropertyChanging("Buyer");
                _Buyer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Buyer");
                OnBuyerChanged();
            }
        }
        private global::System.String _Buyer;
        partial void OnBuyerChanging(global::System.String value);
        partial void OnBuyerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltStkUnit
        {
            get
            {
                return _DfltStkUnit;
            }
            set
            {
                OnDfltStkUnitChanging(value);
                ReportPropertyChanging("DfltStkUnit");
                _DfltStkUnit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltStkUnit");
                OnDfltStkUnitChanged();
            }
        }
        private global::System.String _DfltStkUnit;
        partial void OnDfltStkUnitChanging(global::System.String value);
        partial void OnDfltStkUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltPOUnit
        {
            get
            {
                return _DfltPOUnit;
            }
            set
            {
                OnDfltPOUnitChanging(value);
                ReportPropertyChanging("DfltPOUnit");
                _DfltPOUnit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltPOUnit");
                OnDfltPOUnitChanged();
            }
        }
        private global::System.String _DfltPOUnit;
        partial void OnDfltPOUnitChanging(global::System.String value);
        partial void OnDfltPOUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltSOUnit
        {
            get
            {
                return _DfltSOUnit;
            }
            set
            {
                OnDfltSOUnitChanging(value);
                ReportPropertyChanging("DfltSOUnit");
                _DfltSOUnit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltSOUnit");
                OnDfltSOUnitChanged();
            }
        }
        private global::System.String _DfltSOUnit;
        partial void OnDfltSOUnitChanging(global::System.String value);
        partial void OnDfltSOUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaterialType
        {
            get
            {
                return _MaterialType;
            }
            set
            {
                OnMaterialTypeChanging(value);
                ReportPropertyChanging("MaterialType");
                _MaterialType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaterialType");
                OnMaterialTypeChanged();
            }
        }
        private global::System.String _MaterialType;
        partial void OnMaterialTypeChanging(global::System.String value);
        partial void OnMaterialTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltSlsTaxCat
        {
            get
            {
                return _DfltSlsTaxCat;
            }
            set
            {
                OnDfltSlsTaxCatChanging(value);
                ReportPropertyChanging("DfltSlsTaxCat");
                _DfltSlsTaxCat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltSlsTaxCat");
                OnDfltSlsTaxCatChanged();
            }
        }
        private global::System.String _DfltSlsTaxCat;
        partial void OnDfltSlsTaxCatChanging(global::System.String value);
        partial void OnDfltSlsTaxCatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltSite
        {
            get
            {
                return _DfltSite;
            }
            set
            {
                OnDfltSiteChanging(value);
                ReportPropertyChanging("DfltSite");
                _DfltSite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltSite");
                OnDfltSiteChanged();
            }
        }
        private global::System.String _DfltSite;
        partial void OnDfltSiteChanging(global::System.String value);
        partial void OnDfltSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltLotSerAssign
        {
            get
            {
                return _DfltLotSerAssign;
            }
            set
            {
                OnDfltLotSerAssignChanging(value);
                ReportPropertyChanging("DfltLotSerAssign");
                _DfltLotSerAssign = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltLotSerAssign");
                OnDfltLotSerAssignChanged();
            }
        }
        private global::System.String _DfltLotSerAssign;
        partial void OnDfltLotSerAssignChanging(global::System.String value);
        partial void OnDfltLotSerAssignChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltLotSerFxdTyp
        {
            get
            {
                return _DfltLotSerFxdTyp;
            }
            set
            {
                OnDfltLotSerFxdTypChanging(value);
                ReportPropertyChanging("DfltLotSerFxdTyp");
                _DfltLotSerFxdTyp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltLotSerFxdTyp");
                OnDfltLotSerFxdTypChanged();
            }
        }
        private global::System.String _DfltLotSerFxdTyp;
        partial void OnDfltLotSerFxdTypChanging(global::System.String value);
        partial void OnDfltLotSerFxdTypChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> DfltLotSerFxdLen
        {
            get
            {
                return _DfltLotSerFxdLen;
            }
            set
            {
                OnDfltLotSerFxdLenChanging(value);
                ReportPropertyChanging("DfltLotSerFxdLen");
                _DfltLotSerFxdLen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DfltLotSerFxdLen");
                OnDfltLotSerFxdLenChanged();
            }
        }
        private Nullable<global::System.Int16> _DfltLotSerFxdLen;
        partial void OnDfltLotSerFxdLenChanging(Nullable<global::System.Int16> value);
        partial void OnDfltLotSerFxdLenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltLotSerFxdVal
        {
            get
            {
                return _DfltLotSerFxdVal;
            }
            set
            {
                OnDfltLotSerFxdValChanging(value);
                ReportPropertyChanging("DfltLotSerFxdVal");
                _DfltLotSerFxdVal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltLotSerFxdVal");
                OnDfltLotSerFxdValChanged();
            }
        }
        private global::System.String _DfltLotSerFxdVal;
        partial void OnDfltLotSerFxdValChanging(global::System.String value);
        partial void OnDfltLotSerFxdValChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltLotSerMthd
        {
            get
            {
                return _DfltLotSerMthd;
            }
            set
            {
                OnDfltLotSerMthdChanging(value);
                ReportPropertyChanging("DfltLotSerMthd");
                _DfltLotSerMthd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltLotSerMthd");
                OnDfltLotSerMthdChanged();
            }
        }
        private global::System.String _DfltLotSerMthd;
        partial void OnDfltLotSerMthdChanging(global::System.String value);
        partial void OnDfltLotSerMthdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DfltLotSerNumLen
        {
            get
            {
                return _DfltLotSerNumLen;
            }
            set
            {
                OnDfltLotSerNumLenChanging(value);
                ReportPropertyChanging("DfltLotSerNumLen");
                _DfltLotSerNumLen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DfltLotSerNumLen");
                OnDfltLotSerNumLenChanged();
            }
        }
        private global::System.Int16 _DfltLotSerNumLen;
        partial void OnDfltLotSerNumLenChanging(global::System.Int16 value);
        partial void OnDfltLotSerNumLenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DfltLotSerNumVal
        {
            get
            {
                return _DfltLotSerNumVal;
            }
            set
            {
                OnDfltLotSerNumValChanging(value);
                ReportPropertyChanging("DfltLotSerNumVal");
                _DfltLotSerNumVal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DfltLotSerNumVal");
                OnDfltLotSerNumValChanged();
            }
        }
        private global::System.String _DfltLotSerNumVal;
        partial void OnDfltLotSerNumValChanging(global::System.String value);
        partial void OnDfltLotSerNumValChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DfltLotSerShelfLife
        {
            get
            {
                return _DfltLotSerShelfLife;
            }
            set
            {
                OnDfltLotSerShelfLifeChanging(value);
                ReportPropertyChanging("DfltLotSerShelfLife");
                _DfltLotSerShelfLife = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DfltLotSerShelfLife");
                OnDfltLotSerShelfLifeChanged();
            }
        }
        private global::System.Int16 _DfltLotSerShelfLife;
        partial void OnDfltLotSerShelfLifeChanging(global::System.Int16 value);
        partial void OnDfltLotSerShelfLifeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DfltStkItem
        {
            get
            {
                return _DfltStkItem;
            }
            set
            {
                OnDfltStkItemChanging(value);
                ReportPropertyChanging("DfltStkItem");
                _DfltStkItem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DfltStkItem");
                OnDfltStkItemChanged();
            }
        }
        private global::System.Int16 _DfltStkItem;
        partial void OnDfltStkItemChanging(global::System.Int16 value);
        partial void OnDfltStkItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DfltWarrantyDays
        {
            get
            {
                return _DfltWarrantyDays;
            }
            set
            {
                OnDfltWarrantyDaysChanging(value);
                ReportPropertyChanging("DfltWarrantyDays");
                _DfltWarrantyDays = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DfltWarrantyDays");
                OnDfltWarrantyDaysChanged();
            }
        }
        private global::System.Int16 _DfltWarrantyDays;
        partial void OnDfltWarrantyDaysChanging(global::System.Int16 value);
        partial void OnDfltWarrantyDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Public
        {
            get
            {
                return _Public;
            }
            set
            {
                OnPublicChanging(value);
                ReportPropertyChanging("Public");
                _Public = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Public");
                OnPublicChanged();
            }
        }
        private Nullable<global::System.Boolean> _Public;
        partial void OnPublicChanging(Nullable<global::System.Boolean> value);
        partial void OnPublicChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN20200Model", Name="IN_UnitConversion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IN_UnitConversion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN_UnitConversion object.
        /// </summary>
        /// <param name="unitType">Initial value of the UnitType property.</param>
        /// <param name="classID">Initial value of the ClassID property.</param>
        /// <param name="invtID">Initial value of the InvtID property.</param>
        /// <param name="fromUnit">Initial value of the FromUnit property.</param>
        /// <param name="toUnit">Initial value of the ToUnit property.</param>
        /// <param name="multDiv">Initial value of the MultDiv property.</param>
        /// <param name="cnvFact">Initial value of the CnvFact property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static IN_UnitConversion CreateIN_UnitConversion(global::System.String unitType, global::System.String classID, global::System.String invtID, global::System.String fromUnit, global::System.String toUnit, global::System.String multDiv, global::System.Double cnvFact, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp)
        {
            IN_UnitConversion iN_UnitConversion = new IN_UnitConversion();
            iN_UnitConversion.UnitType = unitType;
            iN_UnitConversion.ClassID = classID;
            iN_UnitConversion.InvtID = invtID;
            iN_UnitConversion.FromUnit = fromUnit;
            iN_UnitConversion.ToUnit = toUnit;
            iN_UnitConversion.MultDiv = multDiv;
            iN_UnitConversion.CnvFact = cnvFact;
            iN_UnitConversion.Crtd_DateTime = crtd_DateTime;
            iN_UnitConversion.Crtd_Prog = crtd_Prog;
            iN_UnitConversion.Crtd_User = crtd_User;
            iN_UnitConversion.LUpd_DateTime = lUpd_DateTime;
            iN_UnitConversion.LUpd_Prog = lUpd_Prog;
            iN_UnitConversion.LUpd_User = lUpd_User;
            iN_UnitConversion.tstamp = tstamp;
            return iN_UnitConversion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnitType
        {
            get
            {
                return _UnitType;
            }
            set
            {
                if (_UnitType != value)
                {
                    OnUnitTypeChanging(value);
                    ReportPropertyChanging("UnitType");
                    _UnitType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UnitType");
                    OnUnitTypeChanged();
                }
            }
        }
        private global::System.String _UnitType;
        partial void OnUnitTypeChanging(global::System.String value);
        partial void OnUnitTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                if (_ClassID != value)
                {
                    OnClassIDChanging(value);
                    ReportPropertyChanging("ClassID");
                    _ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ClassID");
                    OnClassIDChanged();
                }
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvtID
        {
            get
            {
                return _InvtID;
            }
            set
            {
                if (_InvtID != value)
                {
                    OnInvtIDChanging(value);
                    ReportPropertyChanging("InvtID");
                    _InvtID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InvtID");
                    OnInvtIDChanged();
                }
            }
        }
        private global::System.String _InvtID;
        partial void OnInvtIDChanging(global::System.String value);
        partial void OnInvtIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromUnit
        {
            get
            {
                return _FromUnit;
            }
            set
            {
                if (_FromUnit != value)
                {
                    OnFromUnitChanging(value);
                    ReportPropertyChanging("FromUnit");
                    _FromUnit = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FromUnit");
                    OnFromUnitChanged();
                }
            }
        }
        private global::System.String _FromUnit;
        partial void OnFromUnitChanging(global::System.String value);
        partial void OnFromUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToUnit
        {
            get
            {
                return _ToUnit;
            }
            set
            {
                if (_ToUnit != value)
                {
                    OnToUnitChanging(value);
                    ReportPropertyChanging("ToUnit");
                    _ToUnit = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ToUnit");
                    OnToUnitChanged();
                }
            }
        }
        private global::System.String _ToUnit;
        partial void OnToUnitChanging(global::System.String value);
        partial void OnToUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MultDiv
        {
            get
            {
                return _MultDiv;
            }
            set
            {
                OnMultDivChanging(value);
                ReportPropertyChanging("MultDiv");
                _MultDiv = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MultDiv");
                OnMultDivChanged();
            }
        }
        private global::System.String _MultDiv;
        partial void OnMultDivChanging(global::System.String value);
        partial void OnMultDivChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CnvFact
        {
            get
            {
                return _CnvFact;
            }
            set
            {
                OnCnvFactChanging(value);
                ReportPropertyChanging("CnvFact");
                _CnvFact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CnvFact");
                OnCnvFactChanged();
            }
        }
        private global::System.Double _CnvFact;
        partial void OnCnvFactChanging(global::System.Double value);
        partial void OnCnvFactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="IN20200Model", Name="IN20200_pgLoadgetCompany_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class IN20200_pgLoadgetCompany_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN20200_pgLoadgetCompany_Result object.
        /// </summary>
        /// <param name="classID">Initial value of the ClassID property.</param>
        /// <param name="cpnyID">Initial value of the CpnyID property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static IN20200_pgLoadgetCompany_Result CreateIN20200_pgLoadgetCompany_Result(global::System.String classID, global::System.String cpnyID, global::System.Byte[] tstamp)
        {
            IN20200_pgLoadgetCompany_Result iN20200_pgLoadgetCompany_Result = new IN20200_pgLoadgetCompany_Result();
            iN20200_pgLoadgetCompany_Result.ClassID = classID;
            iN20200_pgLoadgetCompany_Result.CpnyID = cpnyID;
            iN20200_pgLoadgetCompany_Result.tstamp = tstamp;
            return iN20200_pgLoadgetCompany_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClassID
        {
            get
            {
                return _ClassID;
            }
            set
            {
                OnClassIDChanging(value);
                ReportPropertyChanging("ClassID");
                _ClassID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClassID");
                OnClassIDChanged();
            }
        }
        private global::System.String _ClassID;
        partial void OnClassIDChanging(global::System.String value);
        partial void OnClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CpnyID
        {
            get
            {
                return _CpnyID;
            }
            set
            {
                OnCpnyIDChanging(value);
                ReportPropertyChanging("CpnyID");
                _CpnyID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CpnyID");
                OnCpnyIDChanged();
            }
        }
        private global::System.String _CpnyID;
        partial void OnCpnyIDChanging(global::System.String value);
        partial void OnCpnyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CpnyName
        {
            get
            {
                return _CpnyName;
            }
            set
            {
                OnCpnyNameChanging(value);
                ReportPropertyChanging("CpnyName");
                _CpnyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CpnyName");
                OnCpnyNameChanged();
            }
        }
        private global::System.String _CpnyName;
        partial void OnCpnyNameChanging(global::System.String value);
        partial void OnCpnyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    }

    #endregion

    
}
