//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IN40100
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IN40100Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IN40100Entities object using the connection string found in the 'IN40100Entities' section of the application configuration file.
        /// </summary>
        public IN40100Entities() : base("name=IN40100Entities", "IN40100Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IN40100Entities object.
        /// </summary>
        public IN40100Entities(string connectionString) : base(connectionString, "IN40100Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IN40100Entities object.
        /// </summary>
        public IN40100Entities(EntityConnection connection) : base(connection, "IN40100Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IN_EndingCost> IN_EndingCost
        {
            get
            {
                if ((_IN_EndingCost == null))
                {
                    _IN_EndingCost = base.CreateObjectSet<IN_EndingCost>("IN_EndingCost");
                }
                return _IN_EndingCost;
            }
        }
        private ObjectSet<IN_EndingCost> _IN_EndingCost;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IN_WrkCosting> IN_WrkCosting
        {
            get
            {
                if ((_IN_WrkCosting == null))
                {
                    _IN_WrkCosting = base.CreateObjectSet<IN_WrkCosting>("IN_WrkCosting");
                }
                return _IN_WrkCosting;
            }
        }
        private ObjectSet<IN_WrkCosting> _IN_WrkCosting;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IN_EndingCost EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIN_EndingCost(IN_EndingCost iN_EndingCost)
        {
            base.AddObject("IN_EndingCost", iN_EndingCost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IN_WrkCosting EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIN_WrkCosting(IN_WrkCosting iN_WrkCosting)
        {
            base.AddObject("IN_WrkCosting", iN_WrkCosting);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="perNbr">No Metadata Documentation available.</param>
        /// <param name="siteID">No Metadata Documentation available.</param>
        /// <param name="type">No Metadata Documentation available.</param>
        public ObjectResult<IN40100_pgGetListItemForCosting_Result> IN40100_pgGetListItemForCosting(global::System.String perNbr, global::System.String siteID, Nullable<global::System.Int16> type)
        {
            ObjectParameter perNbrParameter;
            if (perNbr != null)
            {
                perNbrParameter = new ObjectParameter("PerNbr", perNbr);
            }
            else
            {
                perNbrParameter = new ObjectParameter("PerNbr", typeof(global::System.String));
            }
    
            ObjectParameter siteIDParameter;
            if (siteID != null)
            {
                siteIDParameter = new ObjectParameter("SiteID", siteID);
            }
            else
            {
                siteIDParameter = new ObjectParameter("SiteID", typeof(global::System.String));
            }
    
            ObjectParameter typeParameter;
            if (type.HasValue)
            {
                typeParameter = new ObjectParameter("Type", type);
            }
            else
            {
                typeParameter = new ObjectParameter("Type", typeof(global::System.Int16));
            }
    
            return base.ExecuteFunction<IN40100_pgGetListItemForCosting_Result>("IN40100_pgGetListItemForCosting", perNbrParameter, siteIDParameter, typeParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN40100Model", Name="IN_EndingCost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IN_EndingCost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN_EndingCost object.
        /// </summary>
        /// <param name="perNbr">Initial value of the PerNbr property.</param>
        /// <param name="siteID">Initial value of the SiteID property.</param>
        /// <param name="invtID">Initial value of the InvtID property.</param>
        /// <param name="avgCost">Initial value of the AvgCost property.</param>
        /// <param name="costDate">Initial value of the CostDate property.</param>
        /// <param name="crtd_Datetime">Initial value of the Crtd_Datetime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_Datetime">Initial value of the LUpd_Datetime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static IN_EndingCost CreateIN_EndingCost(global::System.String perNbr, global::System.String siteID, global::System.String invtID, global::System.Double avgCost, global::System.DateTime costDate, global::System.DateTime crtd_Datetime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_Datetime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp)
        {
            IN_EndingCost iN_EndingCost = new IN_EndingCost();
            iN_EndingCost.PerNbr = perNbr;
            iN_EndingCost.SiteID = siteID;
            iN_EndingCost.InvtID = invtID;
            iN_EndingCost.AvgCost = avgCost;
            iN_EndingCost.CostDate = costDate;
            iN_EndingCost.Crtd_Datetime = crtd_Datetime;
            iN_EndingCost.Crtd_Prog = crtd_Prog;
            iN_EndingCost.Crtd_User = crtd_User;
            iN_EndingCost.LUpd_Datetime = lUpd_Datetime;
            iN_EndingCost.LUpd_Prog = lUpd_Prog;
            iN_EndingCost.LUpd_User = lUpd_User;
            iN_EndingCost.tstamp = tstamp;
            return iN_EndingCost;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PerNbr
        {
            get
            {
                return _PerNbr;
            }
            set
            {
                if (_PerNbr != value)
                {
                    OnPerNbrChanging(value);
                    ReportPropertyChanging("PerNbr");
                    _PerNbr = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PerNbr");
                    OnPerNbrChanged();
                }
            }
        }
        private global::System.String _PerNbr;
        partial void OnPerNbrChanging(global::System.String value);
        partial void OnPerNbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                if (_SiteID != value)
                {
                    OnSiteIDChanging(value);
                    ReportPropertyChanging("SiteID");
                    _SiteID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SiteID");
                    OnSiteIDChanged();
                }
            }
        }
        private global::System.String _SiteID;
        partial void OnSiteIDChanging(global::System.String value);
        partial void OnSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvtID
        {
            get
            {
                return _InvtID;
            }
            set
            {
                if (_InvtID != value)
                {
                    OnInvtIDChanging(value);
                    ReportPropertyChanging("InvtID");
                    _InvtID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InvtID");
                    OnInvtIDChanged();
                }
            }
        }
        private global::System.String _InvtID;
        partial void OnInvtIDChanging(global::System.String value);
        partial void OnInvtIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AvgCost
        {
            get
            {
                return _AvgCost;
            }
            set
            {
                OnAvgCostChanging(value);
                ReportPropertyChanging("AvgCost");
                _AvgCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgCost");
                OnAvgCostChanged();
            }
        }
        private global::System.Double _AvgCost;
        partial void OnAvgCostChanging(global::System.Double value);
        partial void OnAvgCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CostDate
        {
            get
            {
                return _CostDate;
            }
            set
            {
                OnCostDateChanging(value);
                ReportPropertyChanging("CostDate");
                _CostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostDate");
                OnCostDateChanged();
            }
        }
        private global::System.DateTime _CostDate;
        partial void OnCostDateChanging(global::System.DateTime value);
        partial void OnCostDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_Datetime
        {
            get
            {
                return _Crtd_Datetime;
            }
            set
            {
                OnCrtd_DatetimeChanging(value);
                ReportPropertyChanging("Crtd_Datetime");
                _Crtd_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_Datetime");
                OnCrtd_DatetimeChanged();
            }
        }
        private global::System.DateTime _Crtd_Datetime;
        partial void OnCrtd_DatetimeChanging(global::System.DateTime value);
        partial void OnCrtd_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_Datetime
        {
            get
            {
                return _LUpd_Datetime;
            }
            set
            {
                OnLUpd_DatetimeChanging(value);
                ReportPropertyChanging("LUpd_Datetime");
                _LUpd_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_Datetime");
                OnLUpd_DatetimeChanged();
            }
        }
        private global::System.DateTime _LUpd_Datetime;
        partial void OnLUpd_DatetimeChanging(global::System.DateTime value);
        partial void OnLUpd_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IN40100Model", Name="IN_WrkCosting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IN_WrkCosting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN_WrkCosting object.
        /// </summary>
        /// <param name="perNbr">Initial value of the PerNbr property.</param>
        /// <param name="siteID">Initial value of the SiteID property.</param>
        /// <param name="invtID">Initial value of the InvtID property.</param>
        /// <param name="machineName">Initial value of the MachineName property.</param>
        /// <param name="crtd_Datetime">Initial value of the Crtd_Datetime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_Datetime">Initial value of the LUpd_Datetime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static IN_WrkCosting CreateIN_WrkCosting(global::System.String perNbr, global::System.String siteID, global::System.String invtID, global::System.String machineName, global::System.DateTime crtd_Datetime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_Datetime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp)
        {
            IN_WrkCosting iN_WrkCosting = new IN_WrkCosting();
            iN_WrkCosting.PerNbr = perNbr;
            iN_WrkCosting.SiteID = siteID;
            iN_WrkCosting.InvtID = invtID;
            iN_WrkCosting.MachineName = machineName;
            iN_WrkCosting.Crtd_Datetime = crtd_Datetime;
            iN_WrkCosting.Crtd_Prog = crtd_Prog;
            iN_WrkCosting.Crtd_User = crtd_User;
            iN_WrkCosting.LUpd_Datetime = lUpd_Datetime;
            iN_WrkCosting.LUpd_Prog = lUpd_Prog;
            iN_WrkCosting.LUpd_User = lUpd_User;
            iN_WrkCosting.tstamp = tstamp;
            return iN_WrkCosting;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PerNbr
        {
            get
            {
                return _PerNbr;
            }
            set
            {
                if (_PerNbr != value)
                {
                    OnPerNbrChanging(value);
                    ReportPropertyChanging("PerNbr");
                    _PerNbr = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PerNbr");
                    OnPerNbrChanged();
                }
            }
        }
        private global::System.String _PerNbr;
        partial void OnPerNbrChanging(global::System.String value);
        partial void OnPerNbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                if (_SiteID != value)
                {
                    OnSiteIDChanging(value);
                    ReportPropertyChanging("SiteID");
                    _SiteID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SiteID");
                    OnSiteIDChanged();
                }
            }
        }
        private global::System.String _SiteID;
        partial void OnSiteIDChanging(global::System.String value);
        partial void OnSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvtID
        {
            get
            {
                return _InvtID;
            }
            set
            {
                if (_InvtID != value)
                {
                    OnInvtIDChanging(value);
                    ReportPropertyChanging("InvtID");
                    _InvtID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InvtID");
                    OnInvtIDChanged();
                }
            }
        }
        private global::System.String _InvtID;
        partial void OnInvtIDChanging(global::System.String value);
        partial void OnInvtIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                OnMachineNameChanging(value);
                ReportPropertyChanging("MachineName");
                _MachineName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MachineName");
                OnMachineNameChanged();
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_Datetime
        {
            get
            {
                return _Crtd_Datetime;
            }
            set
            {
                OnCrtd_DatetimeChanging(value);
                ReportPropertyChanging("Crtd_Datetime");
                _Crtd_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_Datetime");
                OnCrtd_DatetimeChanged();
            }
        }
        private global::System.DateTime _Crtd_Datetime;
        partial void OnCrtd_DatetimeChanging(global::System.DateTime value);
        partial void OnCrtd_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_Datetime
        {
            get
            {
                return _LUpd_Datetime;
            }
            set
            {
                OnLUpd_DatetimeChanging(value);
                ReportPropertyChanging("LUpd_Datetime");
                _LUpd_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_Datetime");
                OnLUpd_DatetimeChanged();
            }
        }
        private global::System.DateTime _LUpd_Datetime;
        partial void OnLUpd_DatetimeChanging(global::System.DateTime value);
        partial void OnLUpd_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="IN40100Model", Name="IN40100_pgGetListItemForCosting_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class IN40100_pgGetListItemForCosting_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IN40100_pgGetListItemForCosting_Result object.
        /// </summary>
        /// <param name="avgCosted">Initial value of the AvgCosted property.</param>
        /// <param name="avgCost">Initial value of the AvgCost property.</param>
        /// <param name="costDate">Initial value of the CostDate property.</param>
        public static IN40100_pgGetListItemForCosting_Result CreateIN40100_pgGetListItemForCosting_Result(global::System.Double avgCosted, global::System.Double avgCost, global::System.DateTime costDate)
        {
            IN40100_pgGetListItemForCosting_Result iN40100_pgGetListItemForCosting_Result = new IN40100_pgGetListItemForCosting_Result();
            iN40100_pgGetListItemForCosting_Result.AvgCosted = avgCosted;
            iN40100_pgGetListItemForCosting_Result.AvgCost = avgCost;
            iN40100_pgGetListItemForCosting_Result.CostDate = costDate;
            return iN40100_pgGetListItemForCosting_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Sel
        {
            get
            {
                return _Sel;
            }
            set
            {
                OnSelChanging(value);
                ReportPropertyChanging("Sel");
                _Sel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sel");
                OnSelChanged();
            }
        }
        private Nullable<global::System.Boolean> _Sel;
        partial void OnSelChanging(Nullable<global::System.Boolean> value);
        partial void OnSelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Invtid
        {
            get
            {
                return _Invtid;
            }
            set
            {
                OnInvtidChanging(value);
                ReportPropertyChanging("Invtid");
                _Invtid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Invtid");
                OnInvtidChanged();
            }
        }
        private global::System.String _Invtid;
        partial void OnInvtidChanging(global::System.String value);
        partial void OnInvtidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                OnSiteIDChanging(value);
                ReportPropertyChanging("SiteID");
                _SiteID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteID");
                OnSiteIDChanged();
            }
        }
        private global::System.String _SiteID;
        partial void OnSiteIDChanging(global::System.String value);
        partial void OnSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> QtySales
        {
            get
            {
                return _QtySales;
            }
            set
            {
                OnQtySalesChanging(value);
                ReportPropertyChanging("QtySales");
                _QtySales = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtySales");
                OnQtySalesChanged();
            }
        }
        private Nullable<global::System.Double> _QtySales;
        partial void OnQtySalesChanging(Nullable<global::System.Double> value);
        partial void OnQtySalesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AvgCosted
        {
            get
            {
                return _AvgCosted;
            }
            set
            {
                OnAvgCostedChanging(value);
                ReportPropertyChanging("AvgCosted");
                _AvgCosted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgCosted");
                OnAvgCostedChanged();
            }
        }
        private global::System.Double _AvgCosted;
        partial void OnAvgCostedChanging(global::System.Double value);
        partial void OnAvgCostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AvgCost
        {
            get
            {
                return _AvgCost;
            }
            set
            {
                OnAvgCostChanging(value);
                ReportPropertyChanging("AvgCost");
                _AvgCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgCost");
                OnAvgCostChanged();
            }
        }
        private global::System.Double _AvgCost;
        partial void OnAvgCostChanging(global::System.Double value);
        partial void OnAvgCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CostDate
        {
            get
            {
                return _CostDate;
            }
            set
            {
                OnCostDateChanging(value);
                ReportPropertyChanging("CostDate");
                _CostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CostDate");
                OnCostDateChanged();
            }
        }
        private global::System.DateTime _CostDate;
        partial void OnCostDateChanging(global::System.DateTime value);
        partial void OnCostDateChanged();

        #endregion

    }

    #endregion

    
}
