//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AR20201
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AR20201Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AR20201Entities object using the connection string found in the 'AR20201Entities' section of the application configuration file.
        /// </summary>
        public AR20201Entities() : base("name=AR20201Entities", "AR20201Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AR20201Entities object.
        /// </summary>
        public AR20201Entities(string connectionString) : base(connectionString, "AR20201Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AR20201Entities object.
        /// </summary>
        public AR20201Entities(EntityConnection connection) : base(connection, "AR20201Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AR_PG> AR_PG
        {
            get
            {
                if ((_AR_PG == null))
                {
                    _AR_PG = base.CreateObjectSet<AR_PG>("AR_PG");
                }
                return _AR_PG;
            }
        }
        private ObjectSet<AR_PG> _AR_PG;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AR_PGCpnyAddr> AR_PGCpnyAddr
        {
            get
            {
                if ((_AR_PGCpnyAddr == null))
                {
                    _AR_PGCpnyAddr = base.CreateObjectSet<AR_PGCpnyAddr>("AR_PGCpnyAddr");
                }
                return _AR_PGCpnyAddr;
            }
        }
        private ObjectSet<AR_PGCpnyAddr> _AR_PGCpnyAddr;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AR_PG EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAR_PG(AR_PG aR_PG)
        {
            base.AddObject("AR_PG", aR_PG);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AR_PGCpnyAddr EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAR_PGCpnyAddr(AR_PGCpnyAddr aR_PGCpnyAddr)
        {
            base.AddObject("AR_PGCpnyAddr", aR_PGCpnyAddr);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="cpnyID">No Metadata Documentation available.</param>
        /// <param name="pGID">No Metadata Documentation available.</param>
        public ObjectResult<AR20201_pgPGCpnyAddr_Result> AR20201_pgPGCpnyAddr(global::System.String userID, global::System.String cpnyID, global::System.String pGID)
        {
            ObjectParameter userIDParameter;
            if (userID != null)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.String));
            }
    
            ObjectParameter cpnyIDParameter;
            if (cpnyID != null)
            {
                cpnyIDParameter = new ObjectParameter("CpnyID", cpnyID);
            }
            else
            {
                cpnyIDParameter = new ObjectParameter("CpnyID", typeof(global::System.String));
            }
    
            ObjectParameter pGIDParameter;
            if (pGID != null)
            {
                pGIDParameter = new ObjectParameter("PGID", pGID);
            }
            else
            {
                pGIDParameter = new ObjectParameter("PGID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<AR20201_pgPGCpnyAddr_Result>("AR20201_pgPGCpnyAddr", userIDParameter, cpnyIDParameter, pGIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="cpnyID">No Metadata Documentation available.</param>
        public ObjectResult<AR20201_ptCpnyAddr_Result> AR20201_ptCpnyAddr(global::System.String userID, global::System.String cpnyID)
        {
            ObjectParameter userIDParameter;
            if (userID != null)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.String));
            }
    
            ObjectParameter cpnyIDParameter;
            if (cpnyID != null)
            {
                cpnyIDParameter = new ObjectParameter("CpnyID", cpnyID);
            }
            else
            {
                cpnyIDParameter = new ObjectParameter("CpnyID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<AR20201_ptCpnyAddr_Result>("AR20201_ptCpnyAddr", userIDParameter, cpnyIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="channel">No Metadata Documentation available.</param>
        public ObjectResult<AR20201_ptCpnyByChannel_Result> AR20201_ptCpnyByChannel(global::System.String userID, global::System.String channel)
        {
            ObjectParameter userIDParameter;
            if (userID != null)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.String));
            }
    
            ObjectParameter channelParameter;
            if (channel != null)
            {
                channelParameter = new ObjectParameter("Channel", channel);
            }
            else
            {
                channelParameter = new ObjectParameter("Channel", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<AR20201_ptCpnyByChannel_Result>("AR20201_ptCpnyByChannel", userIDParameter, channelParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AR20201Model", Name="AR_PG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AR_PG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AR_PG object.
        /// </summary>
        /// <param name="pGID">Initial value of the PGID property.</param>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        /// <param name="pGName">Initial value of the PGName property.</param>
        /// <param name="addr">Initial value of the Addr property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static AR_PG CreateAR_PG(global::System.String pGID, global::System.String branchID, global::System.String pGName, global::System.String addr, global::System.String position, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.Byte[] tstamp)
        {
            AR_PG aR_PG = new AR_PG();
            aR_PG.PGID = pGID;
            aR_PG.BranchID = branchID;
            aR_PG.PGName = pGName;
            aR_PG.Addr = addr;
            aR_PG.Position = position;
            aR_PG.LUpd_DateTime = lUpd_DateTime;
            aR_PG.LUpd_Prog = lUpd_Prog;
            aR_PG.LUpd_User = lUpd_User;
            aR_PG.Crtd_DateTime = crtd_DateTime;
            aR_PG.Crtd_Prog = crtd_Prog;
            aR_PG.Crtd_User = crtd_User;
            aR_PG.tstamp = tstamp;
            return aR_PG;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PGID
        {
            get
            {
                return _PGID;
            }
            set
            {
                if (_PGID != value)
                {
                    OnPGIDChanging(value);
                    ReportPropertyChanging("PGID");
                    _PGID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PGID");
                    OnPGIDChanged();
                }
            }
        }
        private global::System.String _PGID;
        partial void OnPGIDChanging(global::System.String value);
        partial void OnPGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                if (_BranchID != value)
                {
                    OnBranchIDChanging(value);
                    ReportPropertyChanging("BranchID");
                    _BranchID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BranchID");
                    OnBranchIDChanged();
                }
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PGName
        {
            get
            {
                return _PGName;
            }
            set
            {
                OnPGNameChanging(value);
                ReportPropertyChanging("PGName");
                _PGName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PGName");
                OnPGNameChanged();
            }
        }
        private global::System.String _PGName;
        partial void OnPGNameChanging(global::System.String value);
        partial void OnPGNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Addr
        {
            get
            {
                return _Addr;
            }
            set
            {
                OnAddrChanging(value);
                ReportPropertyChanging("Addr");
                _Addr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Addr");
                OnAddrChanged();
            }
        }
        private global::System.String _Addr;
        partial void OnAddrChanging(global::System.String value);
        partial void OnAddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AR20201Model", Name="AR_PGCpnyAddr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AR_PGCpnyAddr : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AR_PGCpnyAddr object.
        /// </summary>
        /// <param name="addrID">Initial value of the AddrID property.</param>
        /// <param name="pGID">Initial value of the PGID property.</param>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        /// <param name="workingTime">Initial value of the WorkingTime property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static AR_PGCpnyAddr CreateAR_PGCpnyAddr(global::System.String addrID, global::System.String pGID, global::System.String branchID, global::System.String workingTime, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.Byte[] tstamp)
        {
            AR_PGCpnyAddr aR_PGCpnyAddr = new AR_PGCpnyAddr();
            aR_PGCpnyAddr.AddrID = addrID;
            aR_PGCpnyAddr.PGID = pGID;
            aR_PGCpnyAddr.BranchID = branchID;
            aR_PGCpnyAddr.WorkingTime = workingTime;
            aR_PGCpnyAddr.LUpd_DateTime = lUpd_DateTime;
            aR_PGCpnyAddr.LUpd_Prog = lUpd_Prog;
            aR_PGCpnyAddr.LUpd_User = lUpd_User;
            aR_PGCpnyAddr.Crtd_DateTime = crtd_DateTime;
            aR_PGCpnyAddr.Crtd_Prog = crtd_Prog;
            aR_PGCpnyAddr.Crtd_User = crtd_User;
            aR_PGCpnyAddr.tstamp = tstamp;
            return aR_PGCpnyAddr;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddrID
        {
            get
            {
                return _AddrID;
            }
            set
            {
                if (_AddrID != value)
                {
                    OnAddrIDChanging(value);
                    ReportPropertyChanging("AddrID");
                    _AddrID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AddrID");
                    OnAddrIDChanged();
                }
            }
        }
        private global::System.String _AddrID;
        partial void OnAddrIDChanging(global::System.String value);
        partial void OnAddrIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PGID
        {
            get
            {
                return _PGID;
            }
            set
            {
                if (_PGID != value)
                {
                    OnPGIDChanging(value);
                    ReportPropertyChanging("PGID");
                    _PGID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PGID");
                    OnPGIDChanged();
                }
            }
        }
        private global::System.String _PGID;
        partial void OnPGIDChanging(global::System.String value);
        partial void OnPGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                if (_BranchID != value)
                {
                    OnBranchIDChanging(value);
                    ReportPropertyChanging("BranchID");
                    _BranchID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BranchID");
                    OnBranchIDChanged();
                }
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WorkingTime
        {
            get
            {
                return _WorkingTime;
            }
            set
            {
                OnWorkingTimeChanging(value);
                ReportPropertyChanging("WorkingTime");
                _WorkingTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WorkingTime");
                OnWorkingTimeChanged();
            }
        }
        private global::System.String _WorkingTime;
        partial void OnWorkingTimeChanging(global::System.String value);
        partial void OnWorkingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AR20201Model", Name="AR20201_pgPGCpnyAddr_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AR20201_pgPGCpnyAddr_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AR20201_pgPGCpnyAddr_Result object.
        /// </summary>
        /// <param name="addrID">Initial value of the AddrID property.</param>
        /// <param name="pGID">Initial value of the PGID property.</param>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        /// <param name="workingTime">Initial value of the WorkingTime property.</param>
        public static AR20201_pgPGCpnyAddr_Result CreateAR20201_pgPGCpnyAddr_Result(global::System.String addrID, global::System.String pGID, global::System.String branchID, global::System.Byte[] tstamp, global::System.String workingTime)
        {
            AR20201_pgPGCpnyAddr_Result aR20201_pgPGCpnyAddr_Result = new AR20201_pgPGCpnyAddr_Result();
            aR20201_pgPGCpnyAddr_Result.AddrID = addrID;
            aR20201_pgPGCpnyAddr_Result.PGID = pGID;
            aR20201_pgPGCpnyAddr_Result.BranchID = branchID;
            aR20201_pgPGCpnyAddr_Result.tstamp = tstamp;
            aR20201_pgPGCpnyAddr_Result.WorkingTime = workingTime;
            return aR20201_pgPGCpnyAddr_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddrID
        {
            get
            {
                return _AddrID;
            }
            set
            {
                OnAddrIDChanging(value);
                ReportPropertyChanging("AddrID");
                _AddrID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddrID");
                OnAddrIDChanged();
            }
        }
        private global::System.String _AddrID;
        partial void OnAddrIDChanging(global::System.String value);
        partial void OnAddrIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr1
        {
            get
            {
                return _Addr1;
            }
            set
            {
                OnAddr1Changing(value);
                ReportPropertyChanging("Addr1");
                _Addr1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr1");
                OnAddr1Changed();
            }
        }
        private global::System.String _Addr1;
        partial void OnAddr1Changing(global::System.String value);
        partial void OnAddr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr2
        {
            get
            {
                return _Addr2;
            }
            set
            {
                OnAddr2Changing(value);
                ReportPropertyChanging("Addr2");
                _Addr2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr2");
                OnAddr2Changed();
            }
        }
        private global::System.String _Addr2;
        partial void OnAddr2Changing(global::System.String value);
        partial void OnAddr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PGID
        {
            get
            {
                return _PGID;
            }
            set
            {
                OnPGIDChanging(value);
                ReportPropertyChanging("PGID");
                _PGID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PGID");
                OnPGIDChanged();
            }
        }
        private global::System.String _PGID;
        partial void OnPGIDChanging(global::System.String value);
        partial void OnPGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                OnBranchIDChanging(value);
                ReportPropertyChanging("BranchID");
                _BranchID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BranchID");
                OnBranchIDChanged();
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WorkingTime
        {
            get
            {
                return _WorkingTime;
            }
            set
            {
                OnWorkingTimeChanging(value);
                ReportPropertyChanging("WorkingTime");
                _WorkingTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WorkingTime");
                OnWorkingTimeChanged();
            }
        }
        private global::System.String _WorkingTime;
        partial void OnWorkingTimeChanging(global::System.String value);
        partial void OnWorkingTimeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AR20201Model", Name="AR20201_ptCpnyAddr_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AR20201_ptCpnyAddr_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AR20201_ptCpnyAddr_Result object.
        /// </summary>
        /// <param name="addrID">Initial value of the AddrID property.</param>
        public static AR20201_ptCpnyAddr_Result CreateAR20201_ptCpnyAddr_Result(global::System.String addrID)
        {
            AR20201_ptCpnyAddr_Result aR20201_ptCpnyAddr_Result = new AR20201_ptCpnyAddr_Result();
            aR20201_ptCpnyAddr_Result.AddrID = addrID;
            return aR20201_ptCpnyAddr_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddrID
        {
            get
            {
                return _AddrID;
            }
            set
            {
                OnAddrIDChanging(value);
                ReportPropertyChanging("AddrID");
                _AddrID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddrID");
                OnAddrIDChanged();
            }
        }
        private global::System.String _AddrID;
        partial void OnAddrIDChanging(global::System.String value);
        partial void OnAddrIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr1
        {
            get
            {
                return _Addr1;
            }
            set
            {
                OnAddr1Changing(value);
                ReportPropertyChanging("Addr1");
                _Addr1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr1");
                OnAddr1Changed();
            }
        }
        private global::System.String _Addr1;
        partial void OnAddr1Changing(global::System.String value);
        partial void OnAddr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr2
        {
            get
            {
                return _Addr2;
            }
            set
            {
                OnAddr2Changing(value);
                ReportPropertyChanging("Addr2");
                _Addr2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr2");
                OnAddr2Changed();
            }
        }
        private global::System.String _Addr2;
        partial void OnAddr2Changing(global::System.String value);
        partial void OnAddr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="AR20201Model", Name="AR20201_ptCpnyByChannel_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class AR20201_ptCpnyByChannel_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AR20201_ptCpnyByChannel_Result object.
        /// </summary>
        /// <param name="cpnyID">Initial value of the CpnyID property.</param>
        public static AR20201_ptCpnyByChannel_Result CreateAR20201_ptCpnyByChannel_Result(global::System.String cpnyID)
        {
            AR20201_ptCpnyByChannel_Result aR20201_ptCpnyByChannel_Result = new AR20201_ptCpnyByChannel_Result();
            aR20201_ptCpnyByChannel_Result.CpnyID = cpnyID;
            return aR20201_ptCpnyByChannel_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CpnyID
        {
            get
            {
                return _CpnyID;
            }
            set
            {
                OnCpnyIDChanging(value);
                ReportPropertyChanging("CpnyID");
                _CpnyID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CpnyID");
                OnCpnyIDChanged();
            }
        }
        private global::System.String _CpnyID;
        partial void OnCpnyIDChanging(global::System.String value);
        partial void OnCpnyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CpnyName
        {
            get
            {
                return _CpnyName;
            }
            set
            {
                OnCpnyNameChanging(value);
                ReportPropertyChanging("CpnyName");
                _CpnyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CpnyName");
                OnCpnyNameChanged();
            }
        }
        private global::System.String _CpnyName;
        partial void OnCpnyNameChanging(global::System.String value);
        partial void OnCpnyNameChanged();

        #endregion

    }

    #endregion

    
}
