'-- ------------------------------------------------------------
'-- Class name    :  clsOM_Setup
'-- Created date  :  5/13/2015
'-- Created by    :  
'-- Updated by    :  
'-- Generated by    :  Class Maker v1.0
'-- ------------------------------------------------------------

'-- Import Libraries --
Imports HQFramework.Common
Imports HQFramework.DAL
Public Class clsOM_Setup
#Region "Constants"
	Private Const PP_OM_Setup As String = "PP_OM_Setup"
#End Region 

#Region "Member Variables"
	Private mvarSetupID As System.String

	Private mvarAutoReleaseAR As System.Int16

	Private mvarAutoReleaseIN As System.Int16

	Private mvarBGWarningMsg As System.Int16

	Private mvarDetDiscG1App As System.Int16

	Private mvarDetDiscG1C1 As System.String

	Private mvarDetDiscG1C2 As System.String

	Private mvarDetDiscG2App As System.Int16

	Private mvarDetDiscG2C1 As System.String

	Private mvarDetDiscG2C2 As System.String

	Private mvarDetDiscG3App As System.Int16

	Private mvarDetDiscG3C1 As System.String

	Private mvarDetDiscG3C2 As System.String

	Private mvarDetDiscG4App As System.Int16

	Private mvarDetDiscG4C1 As System.String

	Private mvarDetDiscG4C2 As System.String

	Private mvarDetDiscG5App As System.Int16

	Private mvarDetDiscG5C1 As System.String

	Private mvarDetDiscG5C2 As System.String

	Private mvarDetDiscG6App As System.Int16

	Private mvarDetDiscG6C1 As System.String

	Private mvarDetDiscG6C2 As System.String

	Private mvarDfltOrderType As System.String

	Private mvarDfltSalesPrice As System.String

	Private mvarDocDiscG1App As System.Int16

	Private mvarDocDiscG1C1 As System.String

	Private mvarDocDiscG1C2 As System.String

	Private mvarDocDiscG2App As System.Int16

	Private mvarDocDiscG2C1 As System.String

	Private mvarDocDiscG2C2 As System.String

	Private mvarDocDiscG3App As System.Int16

	Private mvarDocDiscG3C1 As System.String

	Private mvarDocDiscG3C2 As System.String

	Private mvarDocDiscG4App As System.Int16

	Private mvarDocDiscG4C1 As System.String

	Private mvarDocDiscG4C2 As System.String

	Private mvarDocDiscG5App As System.Int16

	Private mvarDocDiscG5C1 As System.String

	Private mvarDocDiscG5C2 As System.String

	Private mvarDocDiscG6App As System.Int16

	Private mvarDocDiscG6C1 As System.String

	Private mvarDocDiscG6C2 As System.String

	Private mvarEditableSlsPrice As System.Boolean

	Private mvarGroupDiscG10App As System.Int16

	Private mvarGroupDiscG10C1 As System.String

	Private mvarGroupDiscG10C2 As System.String

	Private mvarGroupDiscG11App As System.Int16

	Private mvarGroupDiscG11C1 As System.String

	Private mvarGroupDiscG11C2 As System.String

	Private mvarGroupDiscG12App As System.Int16

	Private mvarGroupDiscG12C1 As System.String

	Private mvarGroupDiscG12C2 As System.String

	Private mvarGroupDiscG1App As System.Int16

	Private mvarGroupDiscG1C1 As System.String

	Private mvarGroupDiscG1C2 As System.String

	Private mvarGroupDiscG2App As System.Int16

	Private mvarGroupDiscG2C1 As System.String

	Private mvarGroupDiscG2C2 As System.String

	Private mvarGroupDiscG3App As System.Int16

	Private mvarGroupDiscG3C1 As System.String

	Private mvarGroupDiscG3C2 As System.String

	Private mvarGroupDiscG4App As System.Int16

	Private mvarGroupDiscG4C1 As System.String

	Private mvarGroupDiscG4C2 As System.String

	Private mvarGroupDiscG5App As System.Int16

	Private mvarGroupDiscG5C1 As System.String

	Private mvarGroupDiscG5C2 As System.String

	Private mvarGroupDiscG6App As System.Int16

	Private mvarGroupDiscG6C1 As System.String

	Private mvarGroupDiscG6C2 As System.String

	Private mvarGroupDiscG7App As System.Int16

	Private mvarGroupDiscG7C1 As System.String

	Private mvarGroupDiscG7C2 As System.String

	Private mvarGroupDiscG8App As System.Int16

	Private mvarGroupDiscG8C1 As System.String

	Private mvarGroupDiscG8C2 As System.String

	Private mvarGroupDiscG9App As System.Int16

	Private mvarGroupDiscG9C1 As System.String

	Private mvarGroupDiscG9C2 As System.String

	Private mvarPOSPrinter As System.String

	Private mvarPrcClsHierarchyLevel As System.Int16

	Private mvarPrefixBat As System.String

	Private mvarPriceSeq00 As System.String

	Private mvarPriceSeq01 As System.String

	Private mvarPriceSeq02 As System.String

	Private mvarPriceSeq03 As System.String

	Private mvarPriceSeq04 As System.String

	Private mvarPriceSeq05 As System.String

	Private mvarProrateDisc As System.Int16

	Private mvarSimpleDiscounts As System.Int16

	Private mvarUseBarCode As System.Int16

	Private mvarUseDiscTerm As System.Int16

	Private mvarVN32Promotion As System.Int16

	Private mvarLUpd_DateTime As System.DateTime

	Private mvarLUpd_Prog As System.String

	Private mvarLUpd_User As System.String

	Private mvarCrtd_DateTime As System.DateTime

	Private mvarCrtd_Prog As System.String

	Private mvarCrtd_User As System.String

	Private mvartstamp As System.String

	Private mvarAutoInvcNbr As System.Boolean

	Private mvarCreditChkRule As System.String

	Private mvarInlcSOFeeDisc As System.Boolean

	Private mvarInlcSOFeeProm As System.Boolean

	Private mvarReqDiscID As System.Boolean

	Private mvarShowCustClass As System.Boolean

	Private mvarShowKPI As System.Boolean

#End Region 

	Private m_Dal As DataAccess
#Region "Constructors"
	Public Sub New()
		m_Dal = New DataAccess
		Reset()
	End Sub
	Public Sub New(ByVal dal As DataAccess)
		m_Dal = dal
		Reset()
	End Sub
#End Region 

#Region "Public Properties"
	Public Property SetupID() As System.String
		Get
			Return mvarSetupID
		End Get
		Set(ByVal Value As System.String)
			mvarSetupID = Value
		End Set
	End Property

	Public Property AutoReleaseAR() As System.Int16
		Get
			Return mvarAutoReleaseAR
		End Get
		Set(ByVal Value As System.Int16)
			mvarAutoReleaseAR = Value
		End Set
	End Property

	Public Property AutoReleaseIN() As System.Int16
		Get
			Return mvarAutoReleaseIN
		End Get
		Set(ByVal Value As System.Int16)
			mvarAutoReleaseIN = Value
		End Set
	End Property

	Public Property BGWarningMsg() As System.Int16
		Get
			Return mvarBGWarningMsg
		End Get
		Set(ByVal Value As System.Int16)
			mvarBGWarningMsg = Value
		End Set
	End Property

	Public Property DetDiscG1App() As System.Int16
		Get
			Return mvarDetDiscG1App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDetDiscG1App = Value
		End Set
	End Property

	Public Property DetDiscG1C1() As System.String
		Get
			Return mvarDetDiscG1C1
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG1C1 = Value
		End Set
	End Property

	Public Property DetDiscG1C2() As System.String
		Get
			Return mvarDetDiscG1C2
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG1C2 = Value
		End Set
	End Property

	Public Property DetDiscG2App() As System.Int16
		Get
			Return mvarDetDiscG2App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDetDiscG2App = Value
		End Set
	End Property

	Public Property DetDiscG2C1() As System.String
		Get
			Return mvarDetDiscG2C1
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG2C1 = Value
		End Set
	End Property

	Public Property DetDiscG2C2() As System.String
		Get
			Return mvarDetDiscG2C2
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG2C2 = Value
		End Set
	End Property

	Public Property DetDiscG3App() As System.Int16
		Get
			Return mvarDetDiscG3App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDetDiscG3App = Value
		End Set
	End Property

	Public Property DetDiscG3C1() As System.String
		Get
			Return mvarDetDiscG3C1
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG3C1 = Value
		End Set
	End Property

	Public Property DetDiscG3C2() As System.String
		Get
			Return mvarDetDiscG3C2
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG3C2 = Value
		End Set
	End Property

	Public Property DetDiscG4App() As System.Int16
		Get
			Return mvarDetDiscG4App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDetDiscG4App = Value
		End Set
	End Property

	Public Property DetDiscG4C1() As System.String
		Get
			Return mvarDetDiscG4C1
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG4C1 = Value
		End Set
	End Property

	Public Property DetDiscG4C2() As System.String
		Get
			Return mvarDetDiscG4C2
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG4C2 = Value
		End Set
	End Property

	Public Property DetDiscG5App() As System.Int16
		Get
			Return mvarDetDiscG5App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDetDiscG5App = Value
		End Set
	End Property

	Public Property DetDiscG5C1() As System.String
		Get
			Return mvarDetDiscG5C1
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG5C1 = Value
		End Set
	End Property

	Public Property DetDiscG5C2() As System.String
		Get
			Return mvarDetDiscG5C2
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG5C2 = Value
		End Set
	End Property

	Public Property DetDiscG6App() As System.Int16
		Get
			Return mvarDetDiscG6App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDetDiscG6App = Value
		End Set
	End Property

	Public Property DetDiscG6C1() As System.String
		Get
			Return mvarDetDiscG6C1
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG6C1 = Value
		End Set
	End Property

	Public Property DetDiscG6C2() As System.String
		Get
			Return mvarDetDiscG6C2
		End Get
		Set(ByVal Value As System.String)
			mvarDetDiscG6C2 = Value
		End Set
	End Property

	Public Property DfltOrderType() As System.String
		Get
			Return mvarDfltOrderType
		End Get
		Set(ByVal Value As System.String)
			mvarDfltOrderType = Value
		End Set
	End Property

	Public Property DfltSalesPrice() As System.String
		Get
			Return mvarDfltSalesPrice
		End Get
		Set(ByVal Value As System.String)
			mvarDfltSalesPrice = Value
		End Set
	End Property

	Public Property DocDiscG1App() As System.Int16
		Get
			Return mvarDocDiscG1App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDocDiscG1App = Value
		End Set
	End Property

	Public Property DocDiscG1C1() As System.String
		Get
			Return mvarDocDiscG1C1
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG1C1 = Value
		End Set
	End Property

	Public Property DocDiscG1C2() As System.String
		Get
			Return mvarDocDiscG1C2
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG1C2 = Value
		End Set
	End Property

	Public Property DocDiscG2App() As System.Int16
		Get
			Return mvarDocDiscG2App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDocDiscG2App = Value
		End Set
	End Property

	Public Property DocDiscG2C1() As System.String
		Get
			Return mvarDocDiscG2C1
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG2C1 = Value
		End Set
	End Property

	Public Property DocDiscG2C2() As System.String
		Get
			Return mvarDocDiscG2C2
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG2C2 = Value
		End Set
	End Property

	Public Property DocDiscG3App() As System.Int16
		Get
			Return mvarDocDiscG3App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDocDiscG3App = Value
		End Set
	End Property

	Public Property DocDiscG3C1() As System.String
		Get
			Return mvarDocDiscG3C1
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG3C1 = Value
		End Set
	End Property

	Public Property DocDiscG3C2() As System.String
		Get
			Return mvarDocDiscG3C2
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG3C2 = Value
		End Set
	End Property

	Public Property DocDiscG4App() As System.Int16
		Get
			Return mvarDocDiscG4App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDocDiscG4App = Value
		End Set
	End Property

	Public Property DocDiscG4C1() As System.String
		Get
			Return mvarDocDiscG4C1
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG4C1 = Value
		End Set
	End Property

	Public Property DocDiscG4C2() As System.String
		Get
			Return mvarDocDiscG4C2
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG4C2 = Value
		End Set
	End Property

	Public Property DocDiscG5App() As System.Int16
		Get
			Return mvarDocDiscG5App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDocDiscG5App = Value
		End Set
	End Property

	Public Property DocDiscG5C1() As System.String
		Get
			Return mvarDocDiscG5C1
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG5C1 = Value
		End Set
	End Property

	Public Property DocDiscG5C2() As System.String
		Get
			Return mvarDocDiscG5C2
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG5C2 = Value
		End Set
	End Property

	Public Property DocDiscG6App() As System.Int16
		Get
			Return mvarDocDiscG6App
		End Get
		Set(ByVal Value As System.Int16)
			mvarDocDiscG6App = Value
		End Set
	End Property

	Public Property DocDiscG6C1() As System.String
		Get
			Return mvarDocDiscG6C1
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG6C1 = Value
		End Set
	End Property

	Public Property DocDiscG6C2() As System.String
		Get
			Return mvarDocDiscG6C2
		End Get
		Set(ByVal Value As System.String)
			mvarDocDiscG6C2 = Value
		End Set
	End Property

	Public Property EditableSlsPrice() As System.Boolean
		Get
			Return mvarEditableSlsPrice
		End Get
		Set(ByVal Value As System.Boolean)
			mvarEditableSlsPrice = Value
		End Set
	End Property

	Public Property GroupDiscG10App() As System.Int16
		Get
			Return mvarGroupDiscG10App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG10App = Value
		End Set
	End Property

	Public Property GroupDiscG10C1() As System.String
		Get
			Return mvarGroupDiscG10C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG10C1 = Value
		End Set
	End Property

	Public Property GroupDiscG10C2() As System.String
		Get
			Return mvarGroupDiscG10C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG10C2 = Value
		End Set
	End Property

	Public Property GroupDiscG11App() As System.Int16
		Get
			Return mvarGroupDiscG11App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG11App = Value
		End Set
	End Property

	Public Property GroupDiscG11C1() As System.String
		Get
			Return mvarGroupDiscG11C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG11C1 = Value
		End Set
	End Property

	Public Property GroupDiscG11C2() As System.String
		Get
			Return mvarGroupDiscG11C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG11C2 = Value
		End Set
	End Property

	Public Property GroupDiscG12App() As System.Int16
		Get
			Return mvarGroupDiscG12App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG12App = Value
		End Set
	End Property

	Public Property GroupDiscG12C1() As System.String
		Get
			Return mvarGroupDiscG12C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG12C1 = Value
		End Set
	End Property

	Public Property GroupDiscG12C2() As System.String
		Get
			Return mvarGroupDiscG12C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG12C2 = Value
		End Set
	End Property

	Public Property GroupDiscG1App() As System.Int16
		Get
			Return mvarGroupDiscG1App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG1App = Value
		End Set
	End Property

	Public Property GroupDiscG1C1() As System.String
		Get
			Return mvarGroupDiscG1C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG1C1 = Value
		End Set
	End Property

	Public Property GroupDiscG1C2() As System.String
		Get
			Return mvarGroupDiscG1C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG1C2 = Value
		End Set
	End Property

	Public Property GroupDiscG2App() As System.Int16
		Get
			Return mvarGroupDiscG2App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG2App = Value
		End Set
	End Property

	Public Property GroupDiscG2C1() As System.String
		Get
			Return mvarGroupDiscG2C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG2C1 = Value
		End Set
	End Property

	Public Property GroupDiscG2C2() As System.String
		Get
			Return mvarGroupDiscG2C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG2C2 = Value
		End Set
	End Property

	Public Property GroupDiscG3App() As System.Int16
		Get
			Return mvarGroupDiscG3App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG3App = Value
		End Set
	End Property

	Public Property GroupDiscG3C1() As System.String
		Get
			Return mvarGroupDiscG3C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG3C1 = Value
		End Set
	End Property

	Public Property GroupDiscG3C2() As System.String
		Get
			Return mvarGroupDiscG3C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG3C2 = Value
		End Set
	End Property

	Public Property GroupDiscG4App() As System.Int16
		Get
			Return mvarGroupDiscG4App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG4App = Value
		End Set
	End Property

	Public Property GroupDiscG4C1() As System.String
		Get
			Return mvarGroupDiscG4C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG4C1 = Value
		End Set
	End Property

	Public Property GroupDiscG4C2() As System.String
		Get
			Return mvarGroupDiscG4C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG4C2 = Value
		End Set
	End Property

	Public Property GroupDiscG5App() As System.Int16
		Get
			Return mvarGroupDiscG5App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG5App = Value
		End Set
	End Property

	Public Property GroupDiscG5C1() As System.String
		Get
			Return mvarGroupDiscG5C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG5C1 = Value
		End Set
	End Property

	Public Property GroupDiscG5C2() As System.String
		Get
			Return mvarGroupDiscG5C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG5C2 = Value
		End Set
	End Property

	Public Property GroupDiscG6App() As System.Int16
		Get
			Return mvarGroupDiscG6App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG6App = Value
		End Set
	End Property

	Public Property GroupDiscG6C1() As System.String
		Get
			Return mvarGroupDiscG6C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG6C1 = Value
		End Set
	End Property

	Public Property GroupDiscG6C2() As System.String
		Get
			Return mvarGroupDiscG6C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG6C2 = Value
		End Set
	End Property

	Public Property GroupDiscG7App() As System.Int16
		Get
			Return mvarGroupDiscG7App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG7App = Value
		End Set
	End Property

	Public Property GroupDiscG7C1() As System.String
		Get
			Return mvarGroupDiscG7C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG7C1 = Value
		End Set
	End Property

	Public Property GroupDiscG7C2() As System.String
		Get
			Return mvarGroupDiscG7C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG7C2 = Value
		End Set
	End Property

	Public Property GroupDiscG8App() As System.Int16
		Get
			Return mvarGroupDiscG8App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG8App = Value
		End Set
	End Property

	Public Property GroupDiscG8C1() As System.String
		Get
			Return mvarGroupDiscG8C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG8C1 = Value
		End Set
	End Property

	Public Property GroupDiscG8C2() As System.String
		Get
			Return mvarGroupDiscG8C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG8C2 = Value
		End Set
	End Property

	Public Property GroupDiscG9App() As System.Int16
		Get
			Return mvarGroupDiscG9App
		End Get
		Set(ByVal Value As System.Int16)
			mvarGroupDiscG9App = Value
		End Set
	End Property

	Public Property GroupDiscG9C1() As System.String
		Get
			Return mvarGroupDiscG9C1
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG9C1 = Value
		End Set
	End Property

	Public Property GroupDiscG9C2() As System.String
		Get
			Return mvarGroupDiscG9C2
		End Get
		Set(ByVal Value As System.String)
			mvarGroupDiscG9C2 = Value
		End Set
	End Property

	Public Property POSPrinter() As System.String
		Get
			Return mvarPOSPrinter
		End Get
		Set(ByVal Value As System.String)
			mvarPOSPrinter = Value
		End Set
	End Property

	Public Property PrcClsHierarchyLevel() As System.Int16
		Get
			Return mvarPrcClsHierarchyLevel
		End Get
		Set(ByVal Value As System.Int16)
			mvarPrcClsHierarchyLevel = Value
		End Set
	End Property

	Public Property PrefixBat() As System.String
		Get
			Return mvarPrefixBat
		End Get
		Set(ByVal Value As System.String)
			mvarPrefixBat = Value
		End Set
	End Property

	Public Property PriceSeq00() As System.String
		Get
			Return mvarPriceSeq00
		End Get
		Set(ByVal Value As System.String)
			mvarPriceSeq00 = Value
		End Set
	End Property

	Public Property PriceSeq01() As System.String
		Get
			Return mvarPriceSeq01
		End Get
		Set(ByVal Value As System.String)
			mvarPriceSeq01 = Value
		End Set
	End Property

	Public Property PriceSeq02() As System.String
		Get
			Return mvarPriceSeq02
		End Get
		Set(ByVal Value As System.String)
			mvarPriceSeq02 = Value
		End Set
	End Property

	Public Property PriceSeq03() As System.String
		Get
			Return mvarPriceSeq03
		End Get
		Set(ByVal Value As System.String)
			mvarPriceSeq03 = Value
		End Set
	End Property

	Public Property PriceSeq04() As System.String
		Get
			Return mvarPriceSeq04
		End Get
		Set(ByVal Value As System.String)
			mvarPriceSeq04 = Value
		End Set
	End Property

	Public Property PriceSeq05() As System.String
		Get
			Return mvarPriceSeq05
		End Get
		Set(ByVal Value As System.String)
			mvarPriceSeq05 = Value
		End Set
	End Property

	Public Property ProrateDisc() As System.Int16
		Get
			Return mvarProrateDisc
		End Get
		Set(ByVal Value As System.Int16)
			mvarProrateDisc = Value
		End Set
	End Property

	Public Property SimpleDiscounts() As System.Int16
		Get
			Return mvarSimpleDiscounts
		End Get
		Set(ByVal Value As System.Int16)
			mvarSimpleDiscounts = Value
		End Set
	End Property

	Public Property UseBarCode() As System.Int16
		Get
			Return mvarUseBarCode
		End Get
		Set(ByVal Value As System.Int16)
			mvarUseBarCode = Value
		End Set
	End Property

	Public Property UseDiscTerm() As System.Int16
		Get
			Return mvarUseDiscTerm
		End Get
		Set(ByVal Value As System.Int16)
			mvarUseDiscTerm = Value
		End Set
	End Property

	Public Property VN32Promotion() As System.Int16
		Get
			Return mvarVN32Promotion
		End Get
		Set(ByVal Value As System.Int16)
			mvarVN32Promotion = Value
		End Set
	End Property

	Public Property LUpd_DateTime() As System.DateTime
		Get
			Return mvarLUpd_DateTime
		End Get
		Set(ByVal Value As System.DateTime)
			mvarLUpd_DateTime = Value
		End Set
	End Property

	Public Property LUpd_Prog() As System.String
		Get
			Return mvarLUpd_Prog
		End Get
		Set(ByVal Value As System.String)
			mvarLUpd_Prog = Value
		End Set
	End Property

	Public Property LUpd_User() As System.String
		Get
			Return mvarLUpd_User
		End Get
		Set(ByVal Value As System.String)
			mvarLUpd_User = Value
		End Set
	End Property

	Public Property Crtd_DateTime() As System.DateTime
		Get
			Return mvarCrtd_DateTime
		End Get
		Set(ByVal Value As System.DateTime)
			mvarCrtd_DateTime = Value
		End Set
	End Property

	Public Property Crtd_Prog() As System.String
		Get
			Return mvarCrtd_Prog
		End Get
		Set(ByVal Value As System.String)
			mvarCrtd_Prog = Value
		End Set
	End Property

	Public Property Crtd_User() As System.String
		Get
			Return mvarCrtd_User
		End Get
		Set(ByVal Value As System.String)
			mvarCrtd_User = Value
		End Set
	End Property

	Public Property tstamp() As System.String
		Get
			Return mvartstamp
		End Get
		Set(ByVal Value As System.String)
			mvartstamp = Value
		End Set
	End Property

	Public Property AutoInvcNbr() As System.Boolean
		Get
			Return mvarAutoInvcNbr
		End Get
		Set(ByVal Value As System.Boolean)
			mvarAutoInvcNbr = Value
		End Set
	End Property

	Public Property CreditChkRule() As System.String
		Get
			Return mvarCreditChkRule
		End Get
		Set(ByVal Value As System.String)
			mvarCreditChkRule = Value
		End Set
	End Property

	Public Property InlcSOFeeDisc() As System.Boolean
		Get
			Return mvarInlcSOFeeDisc
		End Get
		Set(ByVal Value As System.Boolean)
			mvarInlcSOFeeDisc = Value
		End Set
	End Property

	Public Property InlcSOFeeProm() As System.Boolean
		Get
			Return mvarInlcSOFeeProm
		End Get
		Set(ByVal Value As System.Boolean)
			mvarInlcSOFeeProm = Value
		End Set
	End Property

	Public Property ReqDiscID() As System.Boolean
		Get
			Return mvarReqDiscID
		End Get
		Set(ByVal Value As System.Boolean)
			mvarReqDiscID = Value
		End Set
	End Property

	Public Property ShowCustClass() As System.Boolean
		Get
			Return mvarShowCustClass
		End Get
		Set(ByVal Value As System.Boolean)
			mvarShowCustClass = Value
		End Set
	End Property

	Public Property ShowKPI() As System.Boolean
		Get
			Return mvarShowKPI
		End Get
		Set(ByVal Value As System.Boolean)
			mvarShowKPI = Value
		End Set
	End Property

#End Region 

#Region "Public Methods"
	Public Function Add() as Boolean 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "AddNew", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@SetupID", DbType.String,clsCommon.GetValueDBNull(Me.mvarSetupID), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@AutoReleaseAR", DbType.int16,clsCommon.GetValueDBNull(Me.mvarAutoReleaseAR), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@AutoReleaseIN", DbType.int16,clsCommon.GetValueDBNull(Me.mvarAutoReleaseIN), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@BGWarningMsg", DbType.int16,clsCommon.GetValueDBNull(Me.mvarBGWarningMsg), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG1App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDetDiscG1App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG1C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG1C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG1C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG1C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG2App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDetDiscG2App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG2C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG2C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG2C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG2C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG3App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDetDiscG3App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG3C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG3C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG3C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG3C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG4App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDetDiscG4App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG4C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG4C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG4C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG4C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG5App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDetDiscG5App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG5C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG5C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG5C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG5C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG6App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDetDiscG6App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DetDiscG6C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG6C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DetDiscG6C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDetDiscG6C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DfltOrderType", DbType.String,clsCommon.GetValueDBNull(Me.mvarDfltOrderType), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DfltSalesPrice", DbType.String,clsCommon.GetValueDBNull(Me.mvarDfltSalesPrice), ParameterDirection.Input,1 ))
			pc.Add(New ParamStruct("@DocDiscG1App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDocDiscG1App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DocDiscG1C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG1C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG1C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG1C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG2App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDocDiscG2App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DocDiscG2C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG2C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG2C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG2C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG3App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDocDiscG3App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DocDiscG3C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG3C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG3C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG3C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG4App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDocDiscG4App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DocDiscG4C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG4C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG4C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG4C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG5App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDocDiscG5App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DocDiscG5C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG5C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG5C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG5C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG6App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarDocDiscG6App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@DocDiscG6C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG6C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DocDiscG6C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarDocDiscG6C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@EditableSlsPrice", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarEditableSlsPrice), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG10App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG10App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG10C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG10C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG10C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG10C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG11App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG11App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG11C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG11C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG11C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG11C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG12App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG12App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG12C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG12C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG12C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG12C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG1App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG1App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG1C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG1C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG1C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG1C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG2App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG2App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG2C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG2C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG2C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG2C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG3App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG3App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG3C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG3C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG3C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG3C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG4App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG4App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG4C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG4C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG4C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG4C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG5App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG5App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG5C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG5C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG5C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG5C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG6App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG6App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG6C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG6C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG6C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG6C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG7App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG7App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG7C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG7C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG7C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG7C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG8App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG8App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG8C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG8C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG8C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG8C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG9App", DbType.int16,clsCommon.GetValueDBNull(Me.mvarGroupDiscG9App), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@GroupDiscG9C1", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG9C1), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@GroupDiscG9C2", DbType.String,clsCommon.GetValueDBNull(Me.mvarGroupDiscG9C2), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@POSPrinter", DbType.String,clsCommon.GetValueDBNull(Me.mvarPOSPrinter), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@PrcClsHierarchyLevel", DbType.int16,clsCommon.GetValueDBNull(Me.mvarPrcClsHierarchyLevel), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PrefixBat", DbType.String,clsCommon.GetValueDBNull(Me.mvarPrefixBat), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PriceSeq00", DbType.String,clsCommon.GetValueDBNull(Me.mvarPriceSeq00), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PriceSeq01", DbType.String,clsCommon.GetValueDBNull(Me.mvarPriceSeq01), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PriceSeq02", DbType.String,clsCommon.GetValueDBNull(Me.mvarPriceSeq02), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PriceSeq03", DbType.String,clsCommon.GetValueDBNull(Me.mvarPriceSeq03), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PriceSeq04", DbType.String,clsCommon.GetValueDBNull(Me.mvarPriceSeq04), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PriceSeq05", DbType.String,clsCommon.GetValueDBNull(Me.mvarPriceSeq05), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@ProrateDisc", DbType.int16,clsCommon.GetValueDBNull(Me.mvarProrateDisc), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@SimpleDiscounts", DbType.int16,clsCommon.GetValueDBNull(Me.mvarSimpleDiscounts), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@UseBarCode", DbType.int16,clsCommon.GetValueDBNull(Me.mvarUseBarCode), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@UseDiscTerm", DbType.int16,clsCommon.GetValueDBNull(Me.mvarUseDiscTerm), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@VN32Promotion", DbType.int16,clsCommon.GetValueDBNull(Me.mvarVN32Promotion), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@LUpd_DateTime", DbType.DateTime,clsCommon.GetValueDBNull(Me.mvarLUpd_DateTime), ParameterDirection.Input,16 ))
			pc.Add(New ParamStruct("@LUpd_Prog", DbType.String,clsCommon.GetValueDBNull(Me.mvarLUpd_Prog), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@LUpd_User", DbType.String,clsCommon.GetValueDBNull(Me.mvarLUpd_User), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@Crtd_DateTime", DbType.DateTime,clsCommon.GetValueDBNull(Me.mvarCrtd_DateTime), ParameterDirection.Input,16 ))
			pc.Add(New ParamStruct("@Crtd_Prog", DbType.String,clsCommon.GetValueDBNull(Me.mvarCrtd_Prog), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@Crtd_User", DbType.String,clsCommon.GetValueDBNull(Me.mvarCrtd_User), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@tstamp", DbType.String,clsCommon.GetValueDBNull(Me.mvartstamp), ParameterDirection.Input,18 ))
			pc.Add(New ParamStruct("@AutoInvcNbr", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarAutoInvcNbr), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@CreditChkRule", DbType.String,clsCommon.GetValueDBNull(Me.mvarCreditChkRule), ParameterDirection.Input,1 ))
			pc.Add(New ParamStruct("@InlcSOFeeDisc", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarInlcSOFeeDisc), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@InlcSOFeeProm", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarInlcSOFeeProm), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@ReqDiscID", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarReqDiscID), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@ShowCustClass", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarShowCustClass), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@ShowKPI", DbType.Boolean,clsCommon.GetValueDBNull(Me.mvarShowKPI), ParameterDirection.Input,2 ))
			DAL.ExecPreparedSQL(PP_OM_Setup, CommandType.StoredProcedure, pc,"")
		Me.mvarSetupID = clsCommon.GetValue(pc.Item("@SetupID").Value, mvarSetupID.GetType().FullName)
		Return (Me.mvarSetupID <> String.Empty )
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Function Update() as Boolean 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "Update", ParameterDirection.Input,50 ))
			 pc.Add(New ParamStruct("@SetupID",DbType.String, clsCommon.GetValueDBNull(me.mvarSetupID), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@AutoReleaseAR",DbType.int16, clsCommon.GetValueDBNull(me.mvarAutoReleaseAR), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@AutoReleaseIN",DbType.int16, clsCommon.GetValueDBNull(me.mvarAutoReleaseIN), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@BGWarningMsg",DbType.int16, clsCommon.GetValueDBNull(me.mvarBGWarningMsg), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG1App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDetDiscG1App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG1C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG1C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG1C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG1C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG2App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDetDiscG2App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG2C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG2C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG2C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG2C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG3App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDetDiscG3App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG3C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG3C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG3C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG3C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG4App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDetDiscG4App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG4C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG4C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG4C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG4C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG5App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDetDiscG5App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG5C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG5C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG5C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG5C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG6App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDetDiscG6App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DetDiscG6C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG6C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DetDiscG6C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDetDiscG6C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DfltOrderType",DbType.String, clsCommon.GetValueDBNull(me.mvarDfltOrderType), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DfltSalesPrice",DbType.String, clsCommon.GetValueDBNull(me.mvarDfltSalesPrice), ParameterDirection.Input,1 ))
			 pc.Add(New ParamStruct("@DocDiscG1App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDocDiscG1App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DocDiscG1C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG1C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG1C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG1C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG2App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDocDiscG2App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DocDiscG2C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG2C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG2C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG2C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG3App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDocDiscG3App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DocDiscG3C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG3C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG3C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG3C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG4App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDocDiscG4App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DocDiscG4C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG4C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG4C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG4C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG5App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDocDiscG5App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DocDiscG5C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG5C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG5C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG5C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG6App",DbType.int16, clsCommon.GetValueDBNull(me.mvarDocDiscG6App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@DocDiscG6C1",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG6C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DocDiscG6C2",DbType.String, clsCommon.GetValueDBNull(me.mvarDocDiscG6C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@EditableSlsPrice",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarEditableSlsPrice), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG10App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG10App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG10C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG10C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG10C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG10C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG11App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG11App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG11C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG11C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG11C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG11C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG12App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG12App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG12C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG12C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG12C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG12C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG1App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG1App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG1C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG1C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG1C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG1C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG2App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG2App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG2C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG2C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG2C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG2C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG3App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG3App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG3C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG3C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG3C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG3C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG4App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG4App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG4C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG4C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG4C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG4C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG5App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG5App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG5C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG5C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG5C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG5C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG6App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG6App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG6C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG6C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG6C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG6C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG7App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG7App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG7C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG7C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG7C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG7C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG8App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG8App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG8C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG8C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG8C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG8C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG9App",DbType.int16, clsCommon.GetValueDBNull(me.mvarGroupDiscG9App), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@GroupDiscG9C1",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG9C1), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@GroupDiscG9C2",DbType.String, clsCommon.GetValueDBNull(me.mvarGroupDiscG9C2), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@POSPrinter",DbType.String, clsCommon.GetValueDBNull(me.mvarPOSPrinter), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@PrcClsHierarchyLevel",DbType.int16, clsCommon.GetValueDBNull(me.mvarPrcClsHierarchyLevel), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PrefixBat",DbType.String, clsCommon.GetValueDBNull(me.mvarPrefixBat), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PriceSeq00",DbType.String, clsCommon.GetValueDBNull(me.mvarPriceSeq00), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PriceSeq01",DbType.String, clsCommon.GetValueDBNull(me.mvarPriceSeq01), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PriceSeq02",DbType.String, clsCommon.GetValueDBNull(me.mvarPriceSeq02), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PriceSeq03",DbType.String, clsCommon.GetValueDBNull(me.mvarPriceSeq03), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PriceSeq04",DbType.String, clsCommon.GetValueDBNull(me.mvarPriceSeq04), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PriceSeq05",DbType.String, clsCommon.GetValueDBNull(me.mvarPriceSeq05), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@ProrateDisc",DbType.int16, clsCommon.GetValueDBNull(me.mvarProrateDisc), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@SimpleDiscounts",DbType.int16, clsCommon.GetValueDBNull(me.mvarSimpleDiscounts), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@UseBarCode",DbType.int16, clsCommon.GetValueDBNull(me.mvarUseBarCode), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@UseDiscTerm",DbType.int16, clsCommon.GetValueDBNull(me.mvarUseDiscTerm), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@VN32Promotion",DbType.int16, clsCommon.GetValueDBNull(me.mvarVN32Promotion), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@LUpd_DateTime",DbType.DateTime, clsCommon.GetValueDBNull(me.mvarLUpd_DateTime), ParameterDirection.Input,16 ))
			 pc.Add(New ParamStruct("@LUpd_Prog",DbType.String, clsCommon.GetValueDBNull(me.mvarLUpd_Prog), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@LUpd_User",DbType.String, clsCommon.GetValueDBNull(me.mvarLUpd_User), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@Crtd_DateTime",DbType.DateTime, clsCommon.GetValueDBNull(me.mvarCrtd_DateTime), ParameterDirection.Input,16 ))
			 pc.Add(New ParamStruct("@Crtd_Prog",DbType.String, clsCommon.GetValueDBNull(me.mvarCrtd_Prog), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@Crtd_User",DbType.String, clsCommon.GetValueDBNull(me.mvarCrtd_User), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@tstamp",DbType.String, clsCommon.GetValueDBNull(me.mvartstamp), ParameterDirection.Input,18 ))
			 pc.Add(New ParamStruct("@AutoInvcNbr",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarAutoInvcNbr), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@CreditChkRule",DbType.String, clsCommon.GetValueDBNull(me.mvarCreditChkRule), ParameterDirection.Input,1 ))
			 pc.Add(New ParamStruct("@InlcSOFeeDisc",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarInlcSOFeeDisc), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@InlcSOFeeProm",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarInlcSOFeeProm), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@ReqDiscID",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarReqDiscID), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@ShowCustClass",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarShowCustClass), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@ShowKPI",DbType.Boolean, clsCommon.GetValueDBNull(me.mvarShowKPI), ParameterDirection.Input,2 ))
			Return (DAL.ExecNonQuery(PP_OM_Setup, CommandType.StoredProcedure, pc,"") > 0)
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Function Delete(ByVal SetupID As System.String) as Boolean 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "Delete", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@SetupID",DbType.String, clsCommon.GetValueDBNull(SetupID), ParameterDirection.Input,10 ))
			Return (DAL.ExecNonQuery(PP_OM_Setup, CommandType.StoredProcedure, pc,"") > 0)
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Function GetAll(ByVal SetupID As System.String) as DataTable 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			Dim ds As New DataSet
			pc.Add(New ParamStruct("@Action", DbType.String, "GetListData", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@SetupID", DbType.String, clsCommon.GetValueDBNull(SetupID), ParameterDirection.Input, 10 ))
			ds = DAL.ExecDataSet(PP_OM_Setup, CommandType.StoredProcedure, pc,"")
			Dim keys(0) As DataColumn
			Dim column As DataColumn
			column = ds.Tables(0).Columns("SetupID")
			Keys(0) = column
			ds.Tables(0).PrimaryKey = Keys
			Return ds.Tables(0)
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Sub Reset()
		mvarSetupID = String.Empty
		mvarAutoReleaseAR = 0
		mvarAutoReleaseIN = 0
		mvarBGWarningMsg = 0
		mvarDetDiscG1App = 0
		mvarDetDiscG1C1 = String.Empty
		mvarDetDiscG1C2 = String.Empty
		mvarDetDiscG2App = 0
		mvarDetDiscG2C1 = String.Empty
		mvarDetDiscG2C2 = String.Empty
		mvarDetDiscG3App = 0
		mvarDetDiscG3C1 = String.Empty
		mvarDetDiscG3C2 = String.Empty
		mvarDetDiscG4App = 0
		mvarDetDiscG4C1 = String.Empty
		mvarDetDiscG4C2 = String.Empty
		mvarDetDiscG5App = 0
		mvarDetDiscG5C1 = String.Empty
		mvarDetDiscG5C2 = String.Empty
		mvarDetDiscG6App = 0
		mvarDetDiscG6C1 = String.Empty
		mvarDetDiscG6C2 = String.Empty
		mvarDfltOrderType = String.Empty
		mvarDfltSalesPrice = String.Empty
		mvarDocDiscG1App = 0
		mvarDocDiscG1C1 = String.Empty
		mvarDocDiscG1C2 = String.Empty
		mvarDocDiscG2App = 0
		mvarDocDiscG2C1 = String.Empty
		mvarDocDiscG2C2 = String.Empty
		mvarDocDiscG3App = 0
		mvarDocDiscG3C1 = String.Empty
		mvarDocDiscG3C2 = String.Empty
		mvarDocDiscG4App = 0
		mvarDocDiscG4C1 = String.Empty
		mvarDocDiscG4C2 = String.Empty
		mvarDocDiscG5App = 0
		mvarDocDiscG5C1 = String.Empty
		mvarDocDiscG5C2 = String.Empty
		mvarDocDiscG6App = 0
		mvarDocDiscG6C1 = String.Empty
		mvarDocDiscG6C2 = String.Empty
		mvarEditableSlsPrice = False
		mvarGroupDiscG10App = 0
		mvarGroupDiscG10C1 = String.Empty
		mvarGroupDiscG10C2 = String.Empty
		mvarGroupDiscG11App = 0
		mvarGroupDiscG11C1 = String.Empty
		mvarGroupDiscG11C2 = String.Empty
		mvarGroupDiscG12App = 0
		mvarGroupDiscG12C1 = String.Empty
		mvarGroupDiscG12C2 = String.Empty
		mvarGroupDiscG1App = 0
		mvarGroupDiscG1C1 = String.Empty
		mvarGroupDiscG1C2 = String.Empty
		mvarGroupDiscG2App = 0
		mvarGroupDiscG2C1 = String.Empty
		mvarGroupDiscG2C2 = String.Empty
		mvarGroupDiscG3App = 0
		mvarGroupDiscG3C1 = String.Empty
		mvarGroupDiscG3C2 = String.Empty
		mvarGroupDiscG4App = 0
		mvarGroupDiscG4C1 = String.Empty
		mvarGroupDiscG4C2 = String.Empty
		mvarGroupDiscG5App = 0
		mvarGroupDiscG5C1 = String.Empty
		mvarGroupDiscG5C2 = String.Empty
		mvarGroupDiscG6App = 0
		mvarGroupDiscG6C1 = String.Empty
		mvarGroupDiscG6C2 = String.Empty
		mvarGroupDiscG7App = 0
		mvarGroupDiscG7C1 = String.Empty
		mvarGroupDiscG7C2 = String.Empty
		mvarGroupDiscG8App = 0
		mvarGroupDiscG8C1 = String.Empty
		mvarGroupDiscG8C2 = String.Empty
		mvarGroupDiscG9App = 0
		mvarGroupDiscG9C1 = String.Empty
		mvarGroupDiscG9C2 = String.Empty
		mvarPOSPrinter = String.Empty
		mvarPrcClsHierarchyLevel = 0
		mvarPrefixBat = String.Empty
		mvarPriceSeq00 = String.Empty
		mvarPriceSeq01 = String.Empty
		mvarPriceSeq02 = String.Empty
		mvarPriceSeq03 = String.Empty
		mvarPriceSeq04 = String.Empty
		mvarPriceSeq05 = String.Empty
		mvarProrateDisc = 0
		mvarSimpleDiscounts = 0
		mvarUseBarCode = 0
		mvarUseDiscTerm = 0
		mvarVN32Promotion = 0
		mvarLUpd_DateTime = Today
		mvarLUpd_Prog = String.Empty
		mvarLUpd_User = String.Empty
		mvarCrtd_DateTime = Today
		mvarCrtd_Prog = String.Empty
		mvarCrtd_User = String.Empty
		mvartstamp = String.Empty
		mvarAutoInvcNbr = False
		mvarCreditChkRule = String.Empty
		mvarInlcSOFeeDisc = False
		mvarInlcSOFeeProm = False
		mvarReqDiscID = False
		mvarShowCustClass = False
		mvarShowKPI = False
	End Sub
	Public Function GetByKey(ByVal SetupID As System.String) as Boolean 
		Dim DAL As DataAccess = m_Dal
		Dim ds As New DataSet 
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "GetData_ByKey", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@SetupID", DbType.String, clsCommon.GetValueDBNull(SetupID), ParameterDirection.InputOutput, 10 ))
			ds = DAL.ExecDataSet(PP_OM_Setup, CommandType.StoredProcedure, pc,"")
			me.Reset()
			If ds Is Nothing Then
				Return False
			End If
			If ds.Tables(0).Rows.Count > 0 Then
				FillData(ds.Tables(0).Rows(0))
				Return True
			End If
		Catch ex As Exception
			Throw ex 
		End Try
		Return False
	End Function
	Public Sub FillData(row as DataRow)
		mvarSetupID =  clsCommon.GetValue(row("SetupID"), mvarSetupID.GetType().FullName)
		mvarAutoReleaseAR =  clsCommon.GetValue(row("AutoReleaseAR"), mvarAutoReleaseAR.GetType().FullName)
		mvarAutoReleaseIN =  clsCommon.GetValue(row("AutoReleaseIN"), mvarAutoReleaseIN.GetType().FullName)
		mvarBGWarningMsg =  clsCommon.GetValue(row("BGWarningMsg"), mvarBGWarningMsg.GetType().FullName)
		mvarDetDiscG1App =  clsCommon.GetValue(row("DetDiscG1App"), mvarDetDiscG1App.GetType().FullName)
		mvarDetDiscG1C1 =  clsCommon.GetValue(row("DetDiscG1C1"), mvarDetDiscG1C1.GetType().FullName)
		mvarDetDiscG1C2 =  clsCommon.GetValue(row("DetDiscG1C2"), mvarDetDiscG1C2.GetType().FullName)
		mvarDetDiscG2App =  clsCommon.GetValue(row("DetDiscG2App"), mvarDetDiscG2App.GetType().FullName)
		mvarDetDiscG2C1 =  clsCommon.GetValue(row("DetDiscG2C1"), mvarDetDiscG2C1.GetType().FullName)
		mvarDetDiscG2C2 =  clsCommon.GetValue(row("DetDiscG2C2"), mvarDetDiscG2C2.GetType().FullName)
		mvarDetDiscG3App =  clsCommon.GetValue(row("DetDiscG3App"), mvarDetDiscG3App.GetType().FullName)
		mvarDetDiscG3C1 =  clsCommon.GetValue(row("DetDiscG3C1"), mvarDetDiscG3C1.GetType().FullName)
		mvarDetDiscG3C2 =  clsCommon.GetValue(row("DetDiscG3C2"), mvarDetDiscG3C2.GetType().FullName)
		mvarDetDiscG4App =  clsCommon.GetValue(row("DetDiscG4App"), mvarDetDiscG4App.GetType().FullName)
		mvarDetDiscG4C1 =  clsCommon.GetValue(row("DetDiscG4C1"), mvarDetDiscG4C1.GetType().FullName)
		mvarDetDiscG4C2 =  clsCommon.GetValue(row("DetDiscG4C2"), mvarDetDiscG4C2.GetType().FullName)
		mvarDetDiscG5App =  clsCommon.GetValue(row("DetDiscG5App"), mvarDetDiscG5App.GetType().FullName)
		mvarDetDiscG5C1 =  clsCommon.GetValue(row("DetDiscG5C1"), mvarDetDiscG5C1.GetType().FullName)
		mvarDetDiscG5C2 =  clsCommon.GetValue(row("DetDiscG5C2"), mvarDetDiscG5C2.GetType().FullName)
		mvarDetDiscG6App =  clsCommon.GetValue(row("DetDiscG6App"), mvarDetDiscG6App.GetType().FullName)
		mvarDetDiscG6C1 =  clsCommon.GetValue(row("DetDiscG6C1"), mvarDetDiscG6C1.GetType().FullName)
		mvarDetDiscG6C2 =  clsCommon.GetValue(row("DetDiscG6C2"), mvarDetDiscG6C2.GetType().FullName)
		mvarDfltOrderType =  clsCommon.GetValue(row("DfltOrderType"), mvarDfltOrderType.GetType().FullName)
		mvarDfltSalesPrice =  clsCommon.GetValue(row("DfltSalesPrice"), mvarDfltSalesPrice.GetType().FullName)
		mvarDocDiscG1App =  clsCommon.GetValue(row("DocDiscG1App"), mvarDocDiscG1App.GetType().FullName)
		mvarDocDiscG1C1 =  clsCommon.GetValue(row("DocDiscG1C1"), mvarDocDiscG1C1.GetType().FullName)
		mvarDocDiscG1C2 =  clsCommon.GetValue(row("DocDiscG1C2"), mvarDocDiscG1C2.GetType().FullName)
		mvarDocDiscG2App =  clsCommon.GetValue(row("DocDiscG2App"), mvarDocDiscG2App.GetType().FullName)
		mvarDocDiscG2C1 =  clsCommon.GetValue(row("DocDiscG2C1"), mvarDocDiscG2C1.GetType().FullName)
		mvarDocDiscG2C2 =  clsCommon.GetValue(row("DocDiscG2C2"), mvarDocDiscG2C2.GetType().FullName)
		mvarDocDiscG3App =  clsCommon.GetValue(row("DocDiscG3App"), mvarDocDiscG3App.GetType().FullName)
		mvarDocDiscG3C1 =  clsCommon.GetValue(row("DocDiscG3C1"), mvarDocDiscG3C1.GetType().FullName)
		mvarDocDiscG3C2 =  clsCommon.GetValue(row("DocDiscG3C2"), mvarDocDiscG3C2.GetType().FullName)
		mvarDocDiscG4App =  clsCommon.GetValue(row("DocDiscG4App"), mvarDocDiscG4App.GetType().FullName)
		mvarDocDiscG4C1 =  clsCommon.GetValue(row("DocDiscG4C1"), mvarDocDiscG4C1.GetType().FullName)
		mvarDocDiscG4C2 =  clsCommon.GetValue(row("DocDiscG4C2"), mvarDocDiscG4C2.GetType().FullName)
		mvarDocDiscG5App =  clsCommon.GetValue(row("DocDiscG5App"), mvarDocDiscG5App.GetType().FullName)
		mvarDocDiscG5C1 =  clsCommon.GetValue(row("DocDiscG5C1"), mvarDocDiscG5C1.GetType().FullName)
		mvarDocDiscG5C2 =  clsCommon.GetValue(row("DocDiscG5C2"), mvarDocDiscG5C2.GetType().FullName)
		mvarDocDiscG6App =  clsCommon.GetValue(row("DocDiscG6App"), mvarDocDiscG6App.GetType().FullName)
		mvarDocDiscG6C1 =  clsCommon.GetValue(row("DocDiscG6C1"), mvarDocDiscG6C1.GetType().FullName)
		mvarDocDiscG6C2 =  clsCommon.GetValue(row("DocDiscG6C2"), mvarDocDiscG6C2.GetType().FullName)
		mvarEditableSlsPrice =  clsCommon.GetValue(row("EditableSlsPrice"), mvarEditableSlsPrice.GetType().FullName)
		mvarGroupDiscG10App =  clsCommon.GetValue(row("GroupDiscG10App"), mvarGroupDiscG10App.GetType().FullName)
		mvarGroupDiscG10C1 =  clsCommon.GetValue(row("GroupDiscG10C1"), mvarGroupDiscG10C1.GetType().FullName)
		mvarGroupDiscG10C2 =  clsCommon.GetValue(row("GroupDiscG10C2"), mvarGroupDiscG10C2.GetType().FullName)
		mvarGroupDiscG11App =  clsCommon.GetValue(row("GroupDiscG11App"), mvarGroupDiscG11App.GetType().FullName)
		mvarGroupDiscG11C1 =  clsCommon.GetValue(row("GroupDiscG11C1"), mvarGroupDiscG11C1.GetType().FullName)
		mvarGroupDiscG11C2 =  clsCommon.GetValue(row("GroupDiscG11C2"), mvarGroupDiscG11C2.GetType().FullName)
		mvarGroupDiscG12App =  clsCommon.GetValue(row("GroupDiscG12App"), mvarGroupDiscG12App.GetType().FullName)
		mvarGroupDiscG12C1 =  clsCommon.GetValue(row("GroupDiscG12C1"), mvarGroupDiscG12C1.GetType().FullName)
		mvarGroupDiscG12C2 =  clsCommon.GetValue(row("GroupDiscG12C2"), mvarGroupDiscG12C2.GetType().FullName)
		mvarGroupDiscG1App =  clsCommon.GetValue(row("GroupDiscG1App"), mvarGroupDiscG1App.GetType().FullName)
		mvarGroupDiscG1C1 =  clsCommon.GetValue(row("GroupDiscG1C1"), mvarGroupDiscG1C1.GetType().FullName)
		mvarGroupDiscG1C2 =  clsCommon.GetValue(row("GroupDiscG1C2"), mvarGroupDiscG1C2.GetType().FullName)
		mvarGroupDiscG2App =  clsCommon.GetValue(row("GroupDiscG2App"), mvarGroupDiscG2App.GetType().FullName)
		mvarGroupDiscG2C1 =  clsCommon.GetValue(row("GroupDiscG2C1"), mvarGroupDiscG2C1.GetType().FullName)
		mvarGroupDiscG2C2 =  clsCommon.GetValue(row("GroupDiscG2C2"), mvarGroupDiscG2C2.GetType().FullName)
		mvarGroupDiscG3App =  clsCommon.GetValue(row("GroupDiscG3App"), mvarGroupDiscG3App.GetType().FullName)
		mvarGroupDiscG3C1 =  clsCommon.GetValue(row("GroupDiscG3C1"), mvarGroupDiscG3C1.GetType().FullName)
		mvarGroupDiscG3C2 =  clsCommon.GetValue(row("GroupDiscG3C2"), mvarGroupDiscG3C2.GetType().FullName)
		mvarGroupDiscG4App =  clsCommon.GetValue(row("GroupDiscG4App"), mvarGroupDiscG4App.GetType().FullName)
		mvarGroupDiscG4C1 =  clsCommon.GetValue(row("GroupDiscG4C1"), mvarGroupDiscG4C1.GetType().FullName)
		mvarGroupDiscG4C2 =  clsCommon.GetValue(row("GroupDiscG4C2"), mvarGroupDiscG4C2.GetType().FullName)
		mvarGroupDiscG5App =  clsCommon.GetValue(row("GroupDiscG5App"), mvarGroupDiscG5App.GetType().FullName)
		mvarGroupDiscG5C1 =  clsCommon.GetValue(row("GroupDiscG5C1"), mvarGroupDiscG5C1.GetType().FullName)
		mvarGroupDiscG5C2 =  clsCommon.GetValue(row("GroupDiscG5C2"), mvarGroupDiscG5C2.GetType().FullName)
		mvarGroupDiscG6App =  clsCommon.GetValue(row("GroupDiscG6App"), mvarGroupDiscG6App.GetType().FullName)
		mvarGroupDiscG6C1 =  clsCommon.GetValue(row("GroupDiscG6C1"), mvarGroupDiscG6C1.GetType().FullName)
		mvarGroupDiscG6C2 =  clsCommon.GetValue(row("GroupDiscG6C2"), mvarGroupDiscG6C2.GetType().FullName)
		mvarGroupDiscG7App =  clsCommon.GetValue(row("GroupDiscG7App"), mvarGroupDiscG7App.GetType().FullName)
		mvarGroupDiscG7C1 =  clsCommon.GetValue(row("GroupDiscG7C1"), mvarGroupDiscG7C1.GetType().FullName)
		mvarGroupDiscG7C2 =  clsCommon.GetValue(row("GroupDiscG7C2"), mvarGroupDiscG7C2.GetType().FullName)
		mvarGroupDiscG8App =  clsCommon.GetValue(row("GroupDiscG8App"), mvarGroupDiscG8App.GetType().FullName)
		mvarGroupDiscG8C1 =  clsCommon.GetValue(row("GroupDiscG8C1"), mvarGroupDiscG8C1.GetType().FullName)
		mvarGroupDiscG8C2 =  clsCommon.GetValue(row("GroupDiscG8C2"), mvarGroupDiscG8C2.GetType().FullName)
		mvarGroupDiscG9App =  clsCommon.GetValue(row("GroupDiscG9App"), mvarGroupDiscG9App.GetType().FullName)
		mvarGroupDiscG9C1 =  clsCommon.GetValue(row("GroupDiscG9C1"), mvarGroupDiscG9C1.GetType().FullName)
		mvarGroupDiscG9C2 =  clsCommon.GetValue(row("GroupDiscG9C2"), mvarGroupDiscG9C2.GetType().FullName)
		mvarPOSPrinter =  clsCommon.GetValue(row("POSPrinter"), mvarPOSPrinter.GetType().FullName)
		mvarPrcClsHierarchyLevel =  clsCommon.GetValue(row("PrcClsHierarchyLevel"), mvarPrcClsHierarchyLevel.GetType().FullName)
		mvarPrefixBat =  clsCommon.GetValue(row("PrefixBat"), mvarPrefixBat.GetType().FullName)
		mvarPriceSeq00 =  clsCommon.GetValue(row("PriceSeq00"), mvarPriceSeq00.GetType().FullName)
		mvarPriceSeq01 =  clsCommon.GetValue(row("PriceSeq01"), mvarPriceSeq01.GetType().FullName)
		mvarPriceSeq02 =  clsCommon.GetValue(row("PriceSeq02"), mvarPriceSeq02.GetType().FullName)
		mvarPriceSeq03 =  clsCommon.GetValue(row("PriceSeq03"), mvarPriceSeq03.GetType().FullName)
		mvarPriceSeq04 =  clsCommon.GetValue(row("PriceSeq04"), mvarPriceSeq04.GetType().FullName)
		mvarPriceSeq05 =  clsCommon.GetValue(row("PriceSeq05"), mvarPriceSeq05.GetType().FullName)
		mvarProrateDisc =  clsCommon.GetValue(row("ProrateDisc"), mvarProrateDisc.GetType().FullName)
		mvarSimpleDiscounts =  clsCommon.GetValue(row("SimpleDiscounts"), mvarSimpleDiscounts.GetType().FullName)
		mvarUseBarCode =  clsCommon.GetValue(row("UseBarCode"), mvarUseBarCode.GetType().FullName)
		mvarUseDiscTerm =  clsCommon.GetValue(row("UseDiscTerm"), mvarUseDiscTerm.GetType().FullName)
		mvarVN32Promotion =  clsCommon.GetValue(row("VN32Promotion"), mvarVN32Promotion.GetType().FullName)
		mvarLUpd_DateTime =  clsCommon.GetValue(row("LUpd_DateTime"), mvarLUpd_DateTime.GetType().FullName)
		mvarLUpd_Prog =  clsCommon.GetValue(row("LUpd_Prog"), mvarLUpd_Prog.GetType().FullName)
		mvarLUpd_User =  clsCommon.GetValue(row("LUpd_User"), mvarLUpd_User.GetType().FullName)
		mvarCrtd_DateTime =  clsCommon.GetValue(row("Crtd_DateTime"), mvarCrtd_DateTime.GetType().FullName)
		mvarCrtd_Prog =  clsCommon.GetValue(row("Crtd_Prog"), mvarCrtd_Prog.GetType().FullName)
		mvarCrtd_User =  clsCommon.GetValue(row("Crtd_User"), mvarCrtd_User.GetType().FullName)
		mvartstamp =  clsCommon.GetValue(row("tstamp"), mvartstamp.GetType().FullName)
		mvarAutoInvcNbr =  clsCommon.GetValue(row("AutoInvcNbr"), mvarAutoInvcNbr.GetType().FullName)
		mvarCreditChkRule =  clsCommon.GetValue(row("CreditChkRule"), mvarCreditChkRule.GetType().FullName)
		mvarInlcSOFeeDisc =  clsCommon.GetValue(row("InlcSOFeeDisc"), mvarInlcSOFeeDisc.GetType().FullName)
		mvarInlcSOFeeProm =  clsCommon.GetValue(row("InlcSOFeeProm"), mvarInlcSOFeeProm.GetType().FullName)
		mvarReqDiscID =  clsCommon.GetValue(row("ReqDiscID"), mvarReqDiscID.GetType().FullName)
		mvarShowCustClass =  clsCommon.GetValue(row("ShowCustClass"), mvarShowCustClass.GetType().FullName)
		mvarShowKPI =  clsCommon.GetValue(row("ShowKPI"), mvarShowKPI.GetType().FullName)
	End Sub
#End Region 

#Region "Private Methods"
#End Region 

End Class
