'-- ------------------------------------------------------------
'-- Class name    :  clsPO_Detail
'-- Created date  :  5/13/2015
'-- Created by    :  
'-- Updated by    :  
'-- Generated by    :  Class Maker v1.0
'-- ------------------------------------------------------------

'-- Import Libraries --
Imports HQFramework.Common
Imports HQFramework.DAL
Public Class clsPO_Detail
#Region "Constants"
	Private Const PP_PO_Detail As String = "PP_PO_Detail"
#End Region 

#Region "Member Variables"
	Private mvarBranchID As System.String

	Private mvarPONbr As System.String

	Private mvarLineRef As System.String

	Private mvarBlktLineID As System.Int32

	Private mvarBlktLineRef As System.String

	Private mvarCnvFact As System.Double

	Private mvarCostReceived As System.Double

	Private mvarCostReturned As System.Double

	Private mvarCostVouched As System.Double

	Private mvarExtCost As System.Double

	Private mvarExtWeight As System.Double

	Private mvarExtVolume As System.Double

	Private mvarInvtID As System.String

	Private mvarPOFee As System.Double

	Private mvarPromDate As System.DateTime

	Private mvarPurchaseType As System.String

	Private mvarPurchUnit As System.String

	Private mvarQtyOrd As System.Double

	Private mvarQtyRcvd As System.Double

	Private mvarQtyReturned As System.Double

	Private mvarQtyVouched As System.Double

	Private mvarRcptStage As System.String

	Private mvarReasonCd As System.String

	Private mvarReqdDate As System.DateTime

	Private mvarSiteID As System.String

	Private mvarTaxCat As System.String

	Private mvarTranDesc As System.String

	Private mvarUnitCost As System.Double

	Private mvarUnitMultDiv As System.String

	Private mvarUnitWeight As System.Double

	Private mvarUnitVolume As System.Double

	Private mvarVouchStage As System.String

	Private mvarCrtd_DateTime As System.DateTime

	Private mvarCrtd_Prog As System.String

	Private mvarCrtd_User As System.String

	Private mvarLUpd_DateTime As System.DateTime

	Private mvarLUpd_Prog As System.String

	Private mvarLUpd_User As System.String

	Private mvartstamp As System.String

	Private mvarDiscLineRef As System.String

	Private mvarDiscPct As System.Double

	Private mvarDiscAmt As System.Double

	Private mvarDiscSeq As System.String

	Private mvarDiscID As System.String

	Private mvarTxblAmt00 As System.Double

	Private mvarTxblAmt01 As System.Double

	Private mvarTxblAmt02 As System.Double

	Private mvarTxblAmt03 As System.Double

	Private mvarTaxAmt00 As System.Double

	Private mvarTaxAmt01 As System.Double

	Private mvarTaxAmt02 As System.Double

	Private mvarTaxAmt03 As System.Double

	Private mvarTaxID00 As System.String

	Private mvarTaxID01 As System.String

	Private mvarTaxID02 As System.String

	Private mvarTaxID03 As System.String

#End Region 

	Private m_Dal As DataAccess
#Region "Constructors"
	Public Sub New()
		m_Dal = New DataAccess
		Reset()
	End Sub
	Public Sub New(ByVal dal As DataAccess)
		m_Dal = dal
		Reset()
	End Sub
#End Region 

#Region "Public Properties"
	Public Property BranchID() As System.String
		Get
			Return mvarBranchID
		End Get
		Set(ByVal Value As System.String)
			mvarBranchID = Value
		End Set
	End Property

	Public Property PONbr() As System.String
		Get
			Return mvarPONbr
		End Get
		Set(ByVal Value As System.String)
			mvarPONbr = Value
		End Set
	End Property

	Public Property LineRef() As System.String
		Get
			Return mvarLineRef
		End Get
		Set(ByVal Value As System.String)
			mvarLineRef = Value
		End Set
	End Property

	Public Property BlktLineID() As System.Int32
		Get
			Return mvarBlktLineID
		End Get
		Set(ByVal Value As System.Int32)
			mvarBlktLineID = Value
		End Set
	End Property

	Public Property BlktLineRef() As System.String
		Get
			Return mvarBlktLineRef
		End Get
		Set(ByVal Value As System.String)
			mvarBlktLineRef = Value
		End Set
	End Property

	Public Property CnvFact() As System.Double
		Get
			Return mvarCnvFact
		End Get
		Set(ByVal Value As System.Double)
			mvarCnvFact = Value
		End Set
	End Property

	Public Property CostReceived() As System.Double
		Get
			Return mvarCostReceived
		End Get
		Set(ByVal Value As System.Double)
			mvarCostReceived = Value
		End Set
	End Property

	Public Property CostReturned() As System.Double
		Get
			Return mvarCostReturned
		End Get
		Set(ByVal Value As System.Double)
			mvarCostReturned = Value
		End Set
	End Property

	Public Property CostVouched() As System.Double
		Get
			Return mvarCostVouched
		End Get
		Set(ByVal Value As System.Double)
			mvarCostVouched = Value
		End Set
	End Property

	Public Property ExtCost() As System.Double
		Get
			Return mvarExtCost
		End Get
		Set(ByVal Value As System.Double)
			mvarExtCost = Value
		End Set
	End Property

	Public Property ExtWeight() As System.Double
		Get
			Return mvarExtWeight
		End Get
		Set(ByVal Value As System.Double)
			mvarExtWeight = Value
		End Set
	End Property

	Public Property ExtVolume() As System.Double
		Get
			Return mvarExtVolume
		End Get
		Set(ByVal Value As System.Double)
			mvarExtVolume = Value
		End Set
	End Property

	Public Property InvtID() As System.String
		Get
			Return mvarInvtID
		End Get
		Set(ByVal Value As System.String)
			mvarInvtID = Value
		End Set
	End Property

	Public Property POFee() As System.Double
		Get
			Return mvarPOFee
		End Get
		Set(ByVal Value As System.Double)
			mvarPOFee = Value
		End Set
	End Property

	Public Property PromDate() As System.DateTime
		Get
			Return mvarPromDate
		End Get
		Set(ByVal Value As System.DateTime)
			mvarPromDate = Value
		End Set
	End Property

	Public Property PurchaseType() As System.String
		Get
			Return mvarPurchaseType
		End Get
		Set(ByVal Value As System.String)
			mvarPurchaseType = Value
		End Set
	End Property

	Public Property PurchUnit() As System.String
		Get
			Return mvarPurchUnit
		End Get
		Set(ByVal Value As System.String)
			mvarPurchUnit = Value
		End Set
	End Property

	Public Property QtyOrd() As System.Double
		Get
			Return mvarQtyOrd
		End Get
		Set(ByVal Value As System.Double)
			mvarQtyOrd = Value
		End Set
	End Property

	Public Property QtyRcvd() As System.Double
		Get
			Return mvarQtyRcvd
		End Get
		Set(ByVal Value As System.Double)
			mvarQtyRcvd = Value
		End Set
	End Property

	Public Property QtyReturned() As System.Double
		Get
			Return mvarQtyReturned
		End Get
		Set(ByVal Value As System.Double)
			mvarQtyReturned = Value
		End Set
	End Property

	Public Property QtyVouched() As System.Double
		Get
			Return mvarQtyVouched
		End Get
		Set(ByVal Value As System.Double)
			mvarQtyVouched = Value
		End Set
	End Property

	Public Property RcptStage() As System.String
		Get
			Return mvarRcptStage
		End Get
		Set(ByVal Value As System.String)
			mvarRcptStage = Value
		End Set
	End Property

	Public Property ReasonCd() As System.String
		Get
			Return mvarReasonCd
		End Get
		Set(ByVal Value As System.String)
			mvarReasonCd = Value
		End Set
	End Property

	Public Property ReqdDate() As System.DateTime
		Get
			Return mvarReqdDate
		End Get
		Set(ByVal Value As System.DateTime)
			mvarReqdDate = Value
		End Set
	End Property

	Public Property SiteID() As System.String
		Get
			Return mvarSiteID
		End Get
		Set(ByVal Value As System.String)
			mvarSiteID = Value
		End Set
	End Property

	Public Property TaxCat() As System.String
		Get
			Return mvarTaxCat
		End Get
		Set(ByVal Value As System.String)
			mvarTaxCat = Value
		End Set
	End Property

	Public Property TranDesc() As System.String
		Get
			Return mvarTranDesc
		End Get
		Set(ByVal Value As System.String)
			mvarTranDesc = Value
		End Set
	End Property

	Public Property UnitCost() As System.Double
		Get
			Return mvarUnitCost
		End Get
		Set(ByVal Value As System.Double)
			mvarUnitCost = Value
		End Set
	End Property

	Public Property UnitMultDiv() As System.String
		Get
			Return mvarUnitMultDiv
		End Get
		Set(ByVal Value As System.String)
			mvarUnitMultDiv = Value
		End Set
	End Property

	Public Property UnitWeight() As System.Double
		Get
			Return mvarUnitWeight
		End Get
		Set(ByVal Value As System.Double)
			mvarUnitWeight = Value
		End Set
	End Property

	Public Property UnitVolume() As System.Double
		Get
			Return mvarUnitVolume
		End Get
		Set(ByVal Value As System.Double)
			mvarUnitVolume = Value
		End Set
	End Property

	Public Property VouchStage() As System.String
		Get
			Return mvarVouchStage
		End Get
		Set(ByVal Value As System.String)
			mvarVouchStage = Value
		End Set
	End Property

	Public Property Crtd_DateTime() As System.DateTime
		Get
			Return mvarCrtd_DateTime
		End Get
		Set(ByVal Value As System.DateTime)
			mvarCrtd_DateTime = Value
		End Set
	End Property

	Public Property Crtd_Prog() As System.String
		Get
			Return mvarCrtd_Prog
		End Get
		Set(ByVal Value As System.String)
			mvarCrtd_Prog = Value
		End Set
	End Property

	Public Property Crtd_User() As System.String
		Get
			Return mvarCrtd_User
		End Get
		Set(ByVal Value As System.String)
			mvarCrtd_User = Value
		End Set
	End Property

	Public Property LUpd_DateTime() As System.DateTime
		Get
			Return mvarLUpd_DateTime
		End Get
		Set(ByVal Value As System.DateTime)
			mvarLUpd_DateTime = Value
		End Set
	End Property

	Public Property LUpd_Prog() As System.String
		Get
			Return mvarLUpd_Prog
		End Get
		Set(ByVal Value As System.String)
			mvarLUpd_Prog = Value
		End Set
	End Property

	Public Property LUpd_User() As System.String
		Get
			Return mvarLUpd_User
		End Get
		Set(ByVal Value As System.String)
			mvarLUpd_User = Value
		End Set
	End Property

	Public Property tstamp() As System.String
		Get
			Return mvartstamp
		End Get
		Set(ByVal Value As System.String)
			mvartstamp = Value
		End Set
	End Property

	Public Property DiscLineRef() As System.String
		Get
			Return mvarDiscLineRef
		End Get
		Set(ByVal Value As System.String)
			mvarDiscLineRef = Value
		End Set
	End Property

	Public Property DiscPct() As System.Double
		Get
			Return mvarDiscPct
		End Get
		Set(ByVal Value As System.Double)
			mvarDiscPct = Value
		End Set
	End Property

	Public Property DiscAmt() As System.Double
		Get
			Return mvarDiscAmt
		End Get
		Set(ByVal Value As System.Double)
			mvarDiscAmt = Value
		End Set
	End Property

	Public Property DiscSeq() As System.String
		Get
			Return mvarDiscSeq
		End Get
		Set(ByVal Value As System.String)
			mvarDiscSeq = Value
		End Set
	End Property

	Public Property DiscID() As System.String
		Get
			Return mvarDiscID
		End Get
		Set(ByVal Value As System.String)
			mvarDiscID = Value
		End Set
	End Property

	Public Property TxblAmt00() As System.Double
		Get
			Return mvarTxblAmt00
		End Get
		Set(ByVal Value As System.Double)
			mvarTxblAmt00 = Value
		End Set
	End Property

	Public Property TxblAmt01() As System.Double
		Get
			Return mvarTxblAmt01
		End Get
		Set(ByVal Value As System.Double)
			mvarTxblAmt01 = Value
		End Set
	End Property

	Public Property TxblAmt02() As System.Double
		Get
			Return mvarTxblAmt02
		End Get
		Set(ByVal Value As System.Double)
			mvarTxblAmt02 = Value
		End Set
	End Property

	Public Property TxblAmt03() As System.Double
		Get
			Return mvarTxblAmt03
		End Get
		Set(ByVal Value As System.Double)
			mvarTxblAmt03 = Value
		End Set
	End Property

	Public Property TaxAmt00() As System.Double
		Get
			Return mvarTaxAmt00
		End Get
		Set(ByVal Value As System.Double)
			mvarTaxAmt00 = Value
		End Set
	End Property

	Public Property TaxAmt01() As System.Double
		Get
			Return mvarTaxAmt01
		End Get
		Set(ByVal Value As System.Double)
			mvarTaxAmt01 = Value
		End Set
	End Property

	Public Property TaxAmt02() As System.Double
		Get
			Return mvarTaxAmt02
		End Get
		Set(ByVal Value As System.Double)
			mvarTaxAmt02 = Value
		End Set
	End Property

	Public Property TaxAmt03() As System.Double
		Get
			Return mvarTaxAmt03
		End Get
		Set(ByVal Value As System.Double)
			mvarTaxAmt03 = Value
		End Set
	End Property

	Public Property TaxID00() As System.String
		Get
			Return mvarTaxID00
		End Get
		Set(ByVal Value As System.String)
			mvarTaxID00 = Value
		End Set
	End Property

	Public Property TaxID01() As System.String
		Get
			Return mvarTaxID01
		End Get
		Set(ByVal Value As System.String)
			mvarTaxID01 = Value
		End Set
	End Property

	Public Property TaxID02() As System.String
		Get
			Return mvarTaxID02
		End Get
		Set(ByVal Value As System.String)
			mvarTaxID02 = Value
		End Set
	End Property

	Public Property TaxID03() As System.String
		Get
			Return mvarTaxID03
		End Get
		Set(ByVal Value As System.String)
			mvarTaxID03 = Value
		End Set
	End Property

#End Region 

#Region "Public Methods"
	Public Function Add() as Boolean 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "AddNew", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@BranchID", DbType.String,clsCommon.GetValueDBNull(Me.mvarBranchID), ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@PONbr", DbType.String,clsCommon.GetValueDBNull(Me.mvarPONbr), ParameterDirection.Input,100 ))
			pc.Add(New ParamStruct("@LineRef", DbType.String,clsCommon.GetValueDBNull(Me.mvarLineRef), ParameterDirection.Input,5 ))
			pc.Add(New ParamStruct("@BlktLineID", DbType.int32,clsCommon.GetValueDBNull(Me.mvarBlktLineID), ParameterDirection.Input,4 ))
			pc.Add(New ParamStruct("@BlktLineRef", DbType.String,clsCommon.GetValueDBNull(Me.mvarBlktLineRef), ParameterDirection.Input,5 ))
			pc.Add(New ParamStruct("@CnvFact", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarCnvFact), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@CostReceived", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarCostReceived), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@CostReturned", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarCostReturned), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@CostVouched", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarCostVouched), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@ExtCost", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarExtCost), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@ExtWeight", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarExtWeight), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@ExtVolume", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarExtVolume), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@InvtID", DbType.String,clsCommon.GetValueDBNull(Me.mvarInvtID), ParameterDirection.Input,30 ))
			pc.Add(New ParamStruct("@POFee", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarPOFee), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@PromDate", DbType.DateTime,clsCommon.GetValueDBNull(Me.mvarPromDate.Date), ParameterDirection.Input,16 ))
			pc.Add(New ParamStruct("@PurchaseType", DbType.String,clsCommon.GetValueDBNull(Me.mvarPurchaseType), ParameterDirection.Input,2 ))
			pc.Add(New ParamStruct("@PurchUnit", DbType.String,clsCommon.GetValueDBNull(Me.mvarPurchUnit), ParameterDirection.Input,15 ))
			pc.Add(New ParamStruct("@QtyOrd", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarQtyOrd), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@QtyRcvd", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarQtyRcvd), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@QtyReturned", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarQtyReturned), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@QtyVouched", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarQtyVouched), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@RcptStage", DbType.String,clsCommon.GetValueDBNull(Me.mvarRcptStage), ParameterDirection.Input,1 ))
			pc.Add(New ParamStruct("@ReasonCd", DbType.String,clsCommon.GetValueDBNull(Me.mvarReasonCd), ParameterDirection.Input,6 ))
			pc.Add(New ParamStruct("@ReqdDate", DbType.DateTime,clsCommon.GetValueDBNull(Me.mvarReqdDate.Date), ParameterDirection.Input,16 ))
			pc.Add(New ParamStruct("@SiteID", DbType.String,clsCommon.GetValueDBNull(Me.mvarSiteID), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@TaxCat", DbType.String,clsCommon.GetValueDBNull(Me.mvarTaxCat), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@TranDesc", DbType.String,clsCommon.GetValueDBNull(Me.mvarTranDesc), ParameterDirection.Input,100 ))
			pc.Add(New ParamStruct("@UnitCost", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarUnitCost), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@UnitMultDiv", DbType.String,clsCommon.GetValueDBNull(Me.mvarUnitMultDiv), ParameterDirection.Input,1 ))
			pc.Add(New ParamStruct("@UnitWeight", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarUnitWeight), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@UnitVolume", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarUnitVolume), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@VouchStage", DbType.String,clsCommon.GetValueDBNull(Me.mvarVouchStage), ParameterDirection.Input,1 ))
			pc.Add(New ParamStruct("@Crtd_DateTime", DbType.DateTime,clsCommon.GetValueDBNull(Me.mvarCrtd_DateTime), ParameterDirection.Input,16 ))
			pc.Add(New ParamStruct("@Crtd_Prog", DbType.String,clsCommon.GetValueDBNull(Me.mvarCrtd_Prog), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@Crtd_User", DbType.String,clsCommon.GetValueDBNull(Me.mvarCrtd_User), ParameterDirection.Input,30 ))
			pc.Add(New ParamStruct("@LUpd_DateTime", DbType.DateTime,clsCommon.GetValueDBNull(Me.mvarLUpd_DateTime), ParameterDirection.Input,16 ))
			pc.Add(New ParamStruct("@LUpd_Prog", DbType.String,clsCommon.GetValueDBNull(Me.mvarLUpd_Prog), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@LUpd_User", DbType.String,clsCommon.GetValueDBNull(Me.mvarLUpd_User), ParameterDirection.Input,30 ))
			pc.Add(New ParamStruct("@tstamp", DbType.String,clsCommon.GetValueDBNull(Me.mvartstamp), ParameterDirection.Input,18 ))
			pc.Add(New ParamStruct("@DiscLineRef", DbType.String,clsCommon.GetValueDBNull(Me.mvarDiscLineRef), ParameterDirection.Input,5 ))
			pc.Add(New ParamStruct("@DiscPct", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarDiscPct), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@DiscAmt", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarDiscAmt), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@DiscSeq", DbType.String,clsCommon.GetValueDBNull(Me.mvarDiscSeq), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@DiscID", DbType.String,clsCommon.GetValueDBNull(Me.mvarDiscID), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@TxblAmt00", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTxblAmt00), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TxblAmt01", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTxblAmt01), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TxblAmt02", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTxblAmt02), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TxblAmt03", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTxblAmt03), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TaxAmt00", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTaxAmt00), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TaxAmt01", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTaxAmt01), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TaxAmt02", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTaxAmt02), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TaxAmt03", DbType.Decimal,clsCommon.GetValueDBNull(Me.mvarTaxAmt03), ParameterDirection.Input,8 ))
			pc.Add(New ParamStruct("@TaxID00", DbType.String,clsCommon.GetValueDBNull(Me.mvarTaxID00), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@TaxID01", DbType.String,clsCommon.GetValueDBNull(Me.mvarTaxID01), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@TaxID02", DbType.String,clsCommon.GetValueDBNull(Me.mvarTaxID02), ParameterDirection.Input,10 ))
			pc.Add(New ParamStruct("@TaxID03", DbType.String,clsCommon.GetValueDBNull(Me.mvarTaxID03), ParameterDirection.Input,10 ))
			DAL.ExecPreparedSQL(PP_PO_Detail, CommandType.StoredProcedure, pc,"")
		Me.mvarBranchID = clsCommon.GetValue(pc.Item("@BranchID").Value, mvarBranchID.GetType().FullName)
		Return (Me.mvarBranchID <> String.Empty )
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Function Update() as Boolean 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "Update", ParameterDirection.Input,50 ))
			 pc.Add(New ParamStruct("@BranchID",DbType.String, clsCommon.GetValueDBNull(me.mvarBranchID), ParameterDirection.Input,50 ))
			 pc.Add(New ParamStruct("@PONbr",DbType.String, clsCommon.GetValueDBNull(me.mvarPONbr), ParameterDirection.Input,100 ))
			 pc.Add(New ParamStruct("@LineRef",DbType.String, clsCommon.GetValueDBNull(me.mvarLineRef), ParameterDirection.Input,5 ))
			 pc.Add(New ParamStruct("@BlktLineID",DbType.int32, clsCommon.GetValueDBNull(me.mvarBlktLineID), ParameterDirection.Input,4 ))
			 pc.Add(New ParamStruct("@BlktLineRef",DbType.String, clsCommon.GetValueDBNull(me.mvarBlktLineRef), ParameterDirection.Input,5 ))
			 pc.Add(New ParamStruct("@CnvFact",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarCnvFact), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@CostReceived",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarCostReceived), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@CostReturned",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarCostReturned), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@CostVouched",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarCostVouched), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@ExtCost",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarExtCost), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@ExtWeight",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarExtWeight), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@ExtVolume",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarExtVolume), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@InvtID",DbType.String, clsCommon.GetValueDBNull(me.mvarInvtID), ParameterDirection.Input,30 ))
			 pc.Add(New ParamStruct("@POFee",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarPOFee), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@PromDate",DbType.DateTime, clsCommon.GetValueDBNull(me.mvarPromDate.Date), ParameterDirection.Input,16 ))
			 pc.Add(New ParamStruct("@PurchaseType",DbType.String, clsCommon.GetValueDBNull(me.mvarPurchaseType), ParameterDirection.Input,2 ))
			 pc.Add(New ParamStruct("@PurchUnit",DbType.String, clsCommon.GetValueDBNull(me.mvarPurchUnit), ParameterDirection.Input,15 ))
			 pc.Add(New ParamStruct("@QtyOrd",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarQtyOrd), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@QtyRcvd",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarQtyRcvd), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@QtyReturned",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarQtyReturned), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@QtyVouched",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarQtyVouched), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@RcptStage",DbType.String, clsCommon.GetValueDBNull(me.mvarRcptStage), ParameterDirection.Input,1 ))
			 pc.Add(New ParamStruct("@ReasonCd",DbType.String, clsCommon.GetValueDBNull(me.mvarReasonCd), ParameterDirection.Input,6 ))
			 pc.Add(New ParamStruct("@ReqdDate",DbType.DateTime, clsCommon.GetValueDBNull(me.mvarReqdDate.Date), ParameterDirection.Input,16 ))
			 pc.Add(New ParamStruct("@SiteID",DbType.String, clsCommon.GetValueDBNull(me.mvarSiteID), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@TaxCat",DbType.String, clsCommon.GetValueDBNull(me.mvarTaxCat), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@TranDesc",DbType.String, clsCommon.GetValueDBNull(me.mvarTranDesc), ParameterDirection.Input,100 ))
			 pc.Add(New ParamStruct("@UnitCost",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarUnitCost), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@UnitMultDiv",DbType.String, clsCommon.GetValueDBNull(me.mvarUnitMultDiv), ParameterDirection.Input,1 ))
			 pc.Add(New ParamStruct("@UnitWeight",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarUnitWeight), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@UnitVolume",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarUnitVolume), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@VouchStage",DbType.String, clsCommon.GetValueDBNull(me.mvarVouchStage), ParameterDirection.Input,1 ))
			 pc.Add(New ParamStruct("@Crtd_DateTime",DbType.DateTime, clsCommon.GetValueDBNull(me.mvarCrtd_DateTime), ParameterDirection.Input,16 ))
			 pc.Add(New ParamStruct("@Crtd_Prog",DbType.String, clsCommon.GetValueDBNull(me.mvarCrtd_Prog), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@Crtd_User",DbType.String, clsCommon.GetValueDBNull(me.mvarCrtd_User), ParameterDirection.Input,30 ))
			 pc.Add(New ParamStruct("@LUpd_DateTime",DbType.DateTime, clsCommon.GetValueDBNull(me.mvarLUpd_DateTime), ParameterDirection.Input,16 ))
			 pc.Add(New ParamStruct("@LUpd_Prog",DbType.String, clsCommon.GetValueDBNull(me.mvarLUpd_Prog), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@LUpd_User",DbType.String, clsCommon.GetValueDBNull(me.mvarLUpd_User), ParameterDirection.Input,30 ))
			 pc.Add(New ParamStruct("@tstamp",DbType.String, clsCommon.GetValueDBNull(me.mvartstamp), ParameterDirection.Input,18 ))
			 pc.Add(New ParamStruct("@DiscLineRef",DbType.String, clsCommon.GetValueDBNull(me.mvarDiscLineRef), ParameterDirection.Input,5 ))
			 pc.Add(New ParamStruct("@DiscPct",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarDiscPct), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@DiscAmt",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarDiscAmt), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@DiscSeq",DbType.String, clsCommon.GetValueDBNull(me.mvarDiscSeq), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@DiscID",DbType.String, clsCommon.GetValueDBNull(me.mvarDiscID), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@TxblAmt00",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTxblAmt00), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TxblAmt01",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTxblAmt01), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TxblAmt02",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTxblAmt02), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TxblAmt03",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTxblAmt03), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TaxAmt00",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTaxAmt00), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TaxAmt01",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTaxAmt01), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TaxAmt02",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTaxAmt02), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TaxAmt03",DbType.Decimal, clsCommon.GetValueDBNull(me.mvarTaxAmt03), ParameterDirection.Input,8 ))
			 pc.Add(New ParamStruct("@TaxID00",DbType.String, clsCommon.GetValueDBNull(me.mvarTaxID00), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@TaxID01",DbType.String, clsCommon.GetValueDBNull(me.mvarTaxID01), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@TaxID02",DbType.String, clsCommon.GetValueDBNull(me.mvarTaxID02), ParameterDirection.Input,10 ))
			 pc.Add(New ParamStruct("@TaxID03",DbType.String, clsCommon.GetValueDBNull(me.mvarTaxID03), ParameterDirection.Input,10 ))
			Return (DAL.ExecNonQuery(PP_PO_Detail, CommandType.StoredProcedure, pc,"") > 0)
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Function Delete(ByVal BranchID As System.String, ByVal PONbr As System.String, ByVal LineRef As System.String) as Boolean 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "Delete", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@BranchID",DbType.String, clsCommon.GetValueDBNull(BranchID), ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@PONbr",DbType.String, clsCommon.GetValueDBNull(PONbr), ParameterDirection.Input,100 ))
			pc.Add(New ParamStruct("@LineRef",DbType.String, clsCommon.GetValueDBNull(LineRef), ParameterDirection.Input,5 ))
			Return (DAL.ExecNonQuery(PP_PO_Detail, CommandType.StoredProcedure, pc,"") > 0)
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Function GetAll(ByVal BranchID As System.String, ByVal PONbr As System.String, ByVal LineRef As System.String) as DataTable 
		Dim DAL As DataAccess = m_Dal
		Try
			Dim pc As New ParamCollection
			Dim ds As New DataSet
			pc.Add(New ParamStruct("@Action", DbType.String, "GetListData", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@BranchID", DbType.String, clsCommon.GetValueDBNull(BranchID), ParameterDirection.Input, 50 ))
			pc.Add(New ParamStruct("@PONbr", DbType.String, clsCommon.GetValueDBNull(PONbr), ParameterDirection.Input, 100 ))
			pc.Add(New ParamStruct("@LineRef", DbType.String, clsCommon.GetValueDBNull(LineRef), ParameterDirection.Input, 5 ))
			ds = DAL.ExecDataSet(PP_PO_Detail, CommandType.StoredProcedure, pc,"")
			Dim keys(2) As DataColumn
			Dim column As DataColumn
			column = ds.Tables(0).Columns("BranchID")
			Keys(0) = column
			column = ds.Tables(0).Columns("PONbr")
			Keys(1) = column
			column = ds.Tables(0).Columns("LineRef")
			Keys(2) = column
			ds.Tables(0).PrimaryKey = Keys
			Return ds.Tables(0)
		Catch ex As Exception
			Throw ex 
		End Try
	End Function
	Public Sub Reset()
		mvarBranchID = String.Empty
		mvarPONbr = String.Empty
		mvarLineRef = String.Empty
		mvarBlktLineID = 0
		mvarBlktLineRef = String.Empty
		mvarCnvFact = 0
		mvarCostReceived = 0
		mvarCostReturned = 0
		mvarCostVouched = 0
		mvarExtCost = 0
		mvarExtWeight = 0
		mvarExtVolume = 0
		mvarInvtID = String.Empty
		mvarPOFee = 0
		mvarPromDate = Today
		mvarPurchaseType = String.Empty
		mvarPurchUnit = String.Empty
		mvarQtyOrd = 0
		mvarQtyRcvd = 0
		mvarQtyReturned = 0
		mvarQtyVouched = 0
		mvarRcptStage = String.Empty
		mvarReasonCd = String.Empty
		mvarReqdDate = Today
		mvarSiteID = String.Empty
		mvarTaxCat = String.Empty
		mvarTranDesc = String.Empty
		mvarUnitCost = 0
		mvarUnitMultDiv = String.Empty
		mvarUnitWeight = 0
		mvarUnitVolume = 0
		mvarVouchStage = String.Empty
		mvarCrtd_DateTime = Today
		mvarCrtd_Prog = String.Empty
		mvarCrtd_User = String.Empty
		mvarLUpd_DateTime = Today
		mvarLUpd_Prog = String.Empty
		mvarLUpd_User = String.Empty
		mvartstamp = String.Empty
		mvarDiscLineRef = String.Empty
		mvarDiscPct = 0
		mvarDiscAmt = 0
		mvarDiscSeq = String.Empty
		mvarDiscID = String.Empty
		mvarTxblAmt00 = 0
		mvarTxblAmt01 = 0
		mvarTxblAmt02 = 0
		mvarTxblAmt03 = 0
		mvarTaxAmt00 = 0
		mvarTaxAmt01 = 0
		mvarTaxAmt02 = 0
		mvarTaxAmt03 = 0
		mvarTaxID00 = String.Empty
		mvarTaxID01 = String.Empty
		mvarTaxID02 = String.Empty
		mvarTaxID03 = String.Empty
	End Sub
	Public Function GetByKey(ByVal BranchID As System.String, ByVal PONbr As System.String, ByVal LineRef As System.String) as Boolean 
		Dim DAL As DataAccess = m_Dal
		Dim ds As New DataSet 
		Try
			Dim pc As New ParamCollection
			pc.Add(New ParamStruct("@Action", DbType.String, "GetData_ByKey", ParameterDirection.Input,50 ))
			pc.Add(New ParamStruct("@BranchID", DbType.String, clsCommon.GetValueDBNull(BranchID), ParameterDirection.InputOutput, 50 ))
			pc.Add(New ParamStruct("@PONbr", DbType.String, clsCommon.GetValueDBNull(PONbr), ParameterDirection.InputOutput, 100 ))
			pc.Add(New ParamStruct("@LineRef", DbType.String, clsCommon.GetValueDBNull(LineRef), ParameterDirection.InputOutput, 5 ))
			ds = DAL.ExecDataSet(PP_PO_Detail, CommandType.StoredProcedure, pc,"")
			me.Reset()
			If ds Is Nothing Then
				Return False
			End If
			If ds.Tables(0).Rows.Count > 0 Then
				FillData(ds.Tables(0).Rows(0))
				Return True
			End If
		Catch ex As Exception
			Throw ex 
		End Try
		Return False
	End Function
	Public Sub FillData(row as DataRow)
		mvarBranchID =  clsCommon.GetValue(row("BranchID"), mvarBranchID.GetType().FullName)
		mvarPONbr =  clsCommon.GetValue(row("PONbr"), mvarPONbr.GetType().FullName)
		mvarLineRef =  clsCommon.GetValue(row("LineRef"), mvarLineRef.GetType().FullName)
		mvarBlktLineID =  clsCommon.GetValue(row("BlktLineID"), mvarBlktLineID.GetType().FullName)
		mvarBlktLineRef =  clsCommon.GetValue(row("BlktLineRef"), mvarBlktLineRef.GetType().FullName)
		mvarCnvFact =  clsCommon.GetValue(row("CnvFact"), mvarCnvFact.GetType().FullName)
		mvarCostReceived =  clsCommon.GetValue(row("CostReceived"), mvarCostReceived.GetType().FullName)
		mvarCostReturned =  clsCommon.GetValue(row("CostReturned"), mvarCostReturned.GetType().FullName)
		mvarCostVouched =  clsCommon.GetValue(row("CostVouched"), mvarCostVouched.GetType().FullName)
		mvarExtCost =  clsCommon.GetValue(row("ExtCost"), mvarExtCost.GetType().FullName)
		mvarExtWeight =  clsCommon.GetValue(row("ExtWeight"), mvarExtWeight.GetType().FullName)
		mvarExtVolume =  clsCommon.GetValue(row("ExtVolume"), mvarExtVolume.GetType().FullName)
		mvarInvtID =  clsCommon.GetValue(row("InvtID"), mvarInvtID.GetType().FullName)
		mvarPOFee =  clsCommon.GetValue(row("POFee"), mvarPOFee.GetType().FullName)
		mvarPromDate =  clsCommon.GetValue(row("PromDate"), mvarPromDate.GetType().FullName)
		mvarPurchaseType =  clsCommon.GetValue(row("PurchaseType"), mvarPurchaseType.GetType().FullName)
		mvarPurchUnit =  clsCommon.GetValue(row("PurchUnit"), mvarPurchUnit.GetType().FullName)
		mvarQtyOrd =  clsCommon.GetValue(row("QtyOrd"), mvarQtyOrd.GetType().FullName)
		mvarQtyRcvd =  clsCommon.GetValue(row("QtyRcvd"), mvarQtyRcvd.GetType().FullName)
		mvarQtyReturned =  clsCommon.GetValue(row("QtyReturned"), mvarQtyReturned.GetType().FullName)
		mvarQtyVouched =  clsCommon.GetValue(row("QtyVouched"), mvarQtyVouched.GetType().FullName)
		mvarRcptStage =  clsCommon.GetValue(row("RcptStage"), mvarRcptStage.GetType().FullName)
		mvarReasonCd =  clsCommon.GetValue(row("ReasonCd"), mvarReasonCd.GetType().FullName)
		mvarReqdDate =  clsCommon.GetValue(row("ReqdDate"), mvarReqdDate.GetType().FullName)
		mvarSiteID =  clsCommon.GetValue(row("SiteID"), mvarSiteID.GetType().FullName)
		mvarTaxCat =  clsCommon.GetValue(row("TaxCat"), mvarTaxCat.GetType().FullName)
		mvarTranDesc =  clsCommon.GetValue(row("TranDesc"), mvarTranDesc.GetType().FullName)
		mvarUnitCost =  clsCommon.GetValue(row("UnitCost"), mvarUnitCost.GetType().FullName)
		mvarUnitMultDiv =  clsCommon.GetValue(row("UnitMultDiv"), mvarUnitMultDiv.GetType().FullName)
		mvarUnitWeight =  clsCommon.GetValue(row("UnitWeight"), mvarUnitWeight.GetType().FullName)
		mvarUnitVolume =  clsCommon.GetValue(row("UnitVolume"), mvarUnitVolume.GetType().FullName)
		mvarVouchStage =  clsCommon.GetValue(row("VouchStage"), mvarVouchStage.GetType().FullName)
		mvarCrtd_DateTime =  clsCommon.GetValue(row("Crtd_DateTime"), mvarCrtd_DateTime.GetType().FullName)
		mvarCrtd_Prog =  clsCommon.GetValue(row("Crtd_Prog"), mvarCrtd_Prog.GetType().FullName)
		mvarCrtd_User =  clsCommon.GetValue(row("Crtd_User"), mvarCrtd_User.GetType().FullName)
		mvarLUpd_DateTime =  clsCommon.GetValue(row("LUpd_DateTime"), mvarLUpd_DateTime.GetType().FullName)
		mvarLUpd_Prog =  clsCommon.GetValue(row("LUpd_Prog"), mvarLUpd_Prog.GetType().FullName)
		mvarLUpd_User =  clsCommon.GetValue(row("LUpd_User"), mvarLUpd_User.GetType().FullName)
		mvartstamp =  clsCommon.GetValue(row("tstamp"), mvartstamp.GetType().FullName)
		mvarDiscLineRef =  clsCommon.GetValue(row("DiscLineRef"), mvarDiscLineRef.GetType().FullName)
		mvarDiscPct =  clsCommon.GetValue(row("DiscPct"), mvarDiscPct.GetType().FullName)
		mvarDiscAmt =  clsCommon.GetValue(row("DiscAmt"), mvarDiscAmt.GetType().FullName)
		mvarDiscSeq =  clsCommon.GetValue(row("DiscSeq"), mvarDiscSeq.GetType().FullName)
		mvarDiscID =  clsCommon.GetValue(row("DiscID"), mvarDiscID.GetType().FullName)
		mvarTxblAmt00 =  clsCommon.GetValue(row("TxblAmt00"), mvarTxblAmt00.GetType().FullName)
		mvarTxblAmt01 =  clsCommon.GetValue(row("TxblAmt01"), mvarTxblAmt01.GetType().FullName)
		mvarTxblAmt02 =  clsCommon.GetValue(row("TxblAmt02"), mvarTxblAmt02.GetType().FullName)
		mvarTxblAmt03 =  clsCommon.GetValue(row("TxblAmt03"), mvarTxblAmt03.GetType().FullName)
		mvarTaxAmt00 =  clsCommon.GetValue(row("TaxAmt00"), mvarTaxAmt00.GetType().FullName)
		mvarTaxAmt01 =  clsCommon.GetValue(row("TaxAmt01"), mvarTaxAmt01.GetType().FullName)
		mvarTaxAmt02 =  clsCommon.GetValue(row("TaxAmt02"), mvarTaxAmt02.GetType().FullName)
		mvarTaxAmt03 =  clsCommon.GetValue(row("TaxAmt03"), mvarTaxAmt03.GetType().FullName)
		mvarTaxID00 =  clsCommon.GetValue(row("TaxID00"), mvarTaxID00.GetType().FullName)
		mvarTaxID01 =  clsCommon.GetValue(row("TaxID01"), mvarTaxID01.GetType().FullName)
		mvarTaxID02 =  clsCommon.GetValue(row("TaxID02"), mvarTaxID02.GetType().FullName)
		mvarTaxID03 =  clsCommon.GetValue(row("TaxID03"), mvarTaxID03.GetType().FullName)
	End Sub
#End Region 

#Region "Private Methods"
#End Region 

End Class
