//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SA00900
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SA00900Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SA00900Entities object using the connection string found in the 'SA00900Entities' section of the application configuration file.
        /// </summary>
        public SA00900Entities() : base("name=SA00900Entities", "SA00900Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SA00900Entities object.
        /// </summary>
        public SA00900Entities(string connectionString) : base(connectionString, "SA00900Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SA00900Entities object.
        /// </summary>
        public SA00900Entities(EntityConnection connection) : base(connection, "SA00900Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SYS_Language> SYS_Language
        {
            get
            {
                if ((_SYS_Language == null))
                {
                    _SYS_Language = base.CreateObjectSet<SYS_Language>("SYS_Language");
                }
                return _SYS_Language;
            }
        }
        private ObjectSet<SYS_Language> _SYS_Language;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SYS_Language EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSYS_Language(SYS_Language sYS_Language)
        {
            base.AddObject("SYS_Language", sYS_Language);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="langID">No Metadata Documentation available.</param>
        public ObjectResult<SA00900_GetLangJs_Result> SA00900_GetLangJs(Nullable<global::System.Int16> langID)
        {
            ObjectParameter langIDParameter;
            if (langID.HasValue)
            {
                langIDParameter = new ObjectParameter("LangID", langID);
            }
            else
            {
                langIDParameter = new ObjectParameter("LangID", typeof(global::System.Int16));
            }
    
            return base.ExecuteFunction<SA00900_GetLangJs_Result>("SA00900_GetLangJs", langIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SA00900_pgLoadLanguage_Result> SA00900_pgLoadLanguage()
        {
            return base.ExecuteFunction<SA00900_pgLoadLanguage_Result>("SA00900_pgLoadLanguage");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA00900Model", Name="SYS_Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SYS_Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SYS_Language object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="lang00">Initial value of the Lang00 property.</param>
        /// <param name="lang01">Initial value of the Lang01 property.</param>
        /// <param name="crtd_Datetime">Initial value of the Crtd_Datetime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_Datetime">Initial value of the LUpd_Datetime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static SYS_Language CreateSYS_Language(global::System.String code, global::System.String lang00, global::System.String lang01, global::System.DateTime crtd_Datetime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_Datetime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp)
        {
            SYS_Language sYS_Language = new SYS_Language();
            sYS_Language.Code = code;
            sYS_Language.Lang00 = lang00;
            sYS_Language.Lang01 = lang01;
            sYS_Language.Crtd_Datetime = crtd_Datetime;
            sYS_Language.Crtd_Prog = crtd_Prog;
            sYS_Language.Crtd_User = crtd_User;
            sYS_Language.LUpd_Datetime = lUpd_Datetime;
            sYS_Language.LUpd_Prog = lUpd_Prog;
            sYS_Language.LUpd_User = lUpd_User;
            sYS_Language.tstamp = tstamp;
            return sYS_Language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lang00
        {
            get
            {
                return _Lang00;
            }
            set
            {
                OnLang00Changing(value);
                ReportPropertyChanging("Lang00");
                _Lang00 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lang00");
                OnLang00Changed();
            }
        }
        private global::System.String _Lang00;
        partial void OnLang00Changing(global::System.String value);
        partial void OnLang00Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lang01
        {
            get
            {
                return _Lang01;
            }
            set
            {
                OnLang01Changing(value);
                ReportPropertyChanging("Lang01");
                _Lang01 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lang01");
                OnLang01Changed();
            }
        }
        private global::System.String _Lang01;
        partial void OnLang01Changing(global::System.String value);
        partial void OnLang01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang02
        {
            get
            {
                return _Lang02;
            }
            set
            {
                OnLang02Changing(value);
                ReportPropertyChanging("Lang02");
                _Lang02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang02");
                OnLang02Changed();
            }
        }
        private global::System.String _Lang02;
        partial void OnLang02Changing(global::System.String value);
        partial void OnLang02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang03
        {
            get
            {
                return _Lang03;
            }
            set
            {
                OnLang03Changing(value);
                ReportPropertyChanging("Lang03");
                _Lang03 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang03");
                OnLang03Changed();
            }
        }
        private global::System.String _Lang03;
        partial void OnLang03Changing(global::System.String value);
        partial void OnLang03Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang04
        {
            get
            {
                return _Lang04;
            }
            set
            {
                OnLang04Changing(value);
                ReportPropertyChanging("Lang04");
                _Lang04 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang04");
                OnLang04Changed();
            }
        }
        private global::System.String _Lang04;
        partial void OnLang04Changing(global::System.String value);
        partial void OnLang04Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_Datetime
        {
            get
            {
                return _Crtd_Datetime;
            }
            set
            {
                OnCrtd_DatetimeChanging(value);
                ReportPropertyChanging("Crtd_Datetime");
                _Crtd_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_Datetime");
                OnCrtd_DatetimeChanged();
            }
        }
        private global::System.DateTime _Crtd_Datetime;
        partial void OnCrtd_DatetimeChanging(global::System.DateTime value);
        partial void OnCrtd_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_Datetime
        {
            get
            {
                return _LUpd_Datetime;
            }
            set
            {
                OnLUpd_DatetimeChanging(value);
                ReportPropertyChanging("LUpd_Datetime");
                _LUpd_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_Datetime");
                OnLUpd_DatetimeChanged();
            }
        }
        private global::System.DateTime _LUpd_Datetime;
        partial void OnLUpd_DatetimeChanging(global::System.DateTime value);
        partial void OnLUpd_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SA00900Model", Name="SA00900_GetLangJs_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SA00900_GetLangJs_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SA00900_GetLangJs_Result object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static SA00900_GetLangJs_Result CreateSA00900_GetLangJs_Result(global::System.String code)
        {
            SA00900_GetLangJs_Result sA00900_GetLangJs_Result = new SA00900_GetLangJs_Result();
            sA00900_GetLangJs_Result.Code = code;
            return sA00900_GetLangJs_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang
        {
            get
            {
                return _Lang;
            }
            set
            {
                OnLangChanging(value);
                ReportPropertyChanging("Lang");
                _Lang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang");
                OnLangChanged();
            }
        }
        private global::System.String _Lang;
        partial void OnLangChanging(global::System.String value);
        partial void OnLangChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SA00900Model", Name="SA00900_pgLoadLanguage_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SA00900_pgLoadLanguage_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SA00900_pgLoadLanguage_Result object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="lang00">Initial value of the Lang00 property.</param>
        /// <param name="lang01">Initial value of the Lang01 property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static SA00900_pgLoadLanguage_Result CreateSA00900_pgLoadLanguage_Result(global::System.String code, global::System.String lang00, global::System.String lang01, global::System.Byte[] tstamp)
        {
            SA00900_pgLoadLanguage_Result sA00900_pgLoadLanguage_Result = new SA00900_pgLoadLanguage_Result();
            sA00900_pgLoadLanguage_Result.Code = code;
            sA00900_pgLoadLanguage_Result.Lang00 = lang00;
            sA00900_pgLoadLanguage_Result.Lang01 = lang01;
            sA00900_pgLoadLanguage_Result.tstamp = tstamp;
            return sA00900_pgLoadLanguage_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lang00
        {
            get
            {
                return _Lang00;
            }
            set
            {
                OnLang00Changing(value);
                ReportPropertyChanging("Lang00");
                _Lang00 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lang00");
                OnLang00Changed();
            }
        }
        private global::System.String _Lang00;
        partial void OnLang00Changing(global::System.String value);
        partial void OnLang00Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lang01
        {
            get
            {
                return _Lang01;
            }
            set
            {
                OnLang01Changing(value);
                ReportPropertyChanging("Lang01");
                _Lang01 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lang01");
                OnLang01Changed();
            }
        }
        private global::System.String _Lang01;
        partial void OnLang01Changing(global::System.String value);
        partial void OnLang01Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang02
        {
            get
            {
                return _Lang02;
            }
            set
            {
                OnLang02Changing(value);
                ReportPropertyChanging("Lang02");
                _Lang02 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang02");
                OnLang02Changed();
            }
        }
        private global::System.String _Lang02;
        partial void OnLang02Changing(global::System.String value);
        partial void OnLang02Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang03
        {
            get
            {
                return _Lang03;
            }
            set
            {
                OnLang03Changing(value);
                ReportPropertyChanging("Lang03");
                _Lang03 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang03");
                OnLang03Changed();
            }
        }
        private global::System.String _Lang03;
        partial void OnLang03Changing(global::System.String value);
        partial void OnLang03Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lang04
        {
            get
            {
                return _Lang04;
            }
            set
            {
                OnLang04Changing(value);
                ReportPropertyChanging("Lang04");
                _Lang04 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lang04");
                OnLang04Changed();
            }
        }
        private global::System.String _Lang04;
        partial void OnLang04Changing(global::System.String value);
        partial void OnLang04Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    }

    #endregion

    
}
