//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OM22200
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OM22200Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OM22200Entities object using the connection string found in the 'OM22200Entities' section of the application configuration file.
        /// </summary>
        public OM22200Entities() : base("name=OM22200Entities", "OM22200Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OM22200Entities object.
        /// </summary>
        public OM22200Entities(string connectionString) : base(connectionString, "OM22200Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OM22200Entities object.
        /// </summary>
        public OM22200Entities(EntityConnection connection) : base(connection, "OM22200Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OM_PJP> OM_PJP
        {
            get
            {
                if ((_OM_PJP == null))
                {
                    _OM_PJP = base.CreateObjectSet<OM_PJP>("OM_PJP");
                }
                return _OM_PJP;
            }
        }
        private ObjectSet<OM_PJP> _OM_PJP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OM_SalesRouteMaster> OM_SalesRouteMaster
        {
            get
            {
                if ((_OM_SalesRouteMaster == null))
                {
                    _OM_SalesRouteMaster = base.CreateObjectSet<OM_SalesRouteMaster>("OM_SalesRouteMaster");
                }
                return _OM_SalesRouteMaster;
            }
        }
        private ObjectSet<OM_SalesRouteMaster> _OM_SalesRouteMaster;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OM_PJP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOM_PJP(OM_PJP oM_PJP)
        {
            base.AddObject("OM_PJP", oM_PJP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OM_SalesRouteMaster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOM_SalesRouteMaster(OM_SalesRouteMaster oM_SalesRouteMaster)
        {
            base.AddObject("OM_SalesRouteMaster", oM_SalesRouteMaster);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="branchID">No Metadata Documentation available.</param>
        /// <param name="pJPID">No Metadata Documentation available.</param>
        /// <param name="routeID">No Metadata Documentation available.</param>
        /// <param name="slsperID">No Metadata Documentation available.</param>
        public ObjectResult<OM22200_pgSaleRouteMaster_Result> OM22200_pgSaleRouteMaster(global::System.String userID, global::System.String branchID, global::System.String pJPID, global::System.String routeID, global::System.String slsperID)
        {
            ObjectParameter userIDParameter;
            if (userID != null)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.String));
            }
    
            ObjectParameter branchIDParameter;
            if (branchID != null)
            {
                branchIDParameter = new ObjectParameter("BranchID", branchID);
            }
            else
            {
                branchIDParameter = new ObjectParameter("BranchID", typeof(global::System.String));
            }
    
            ObjectParameter pJPIDParameter;
            if (pJPID != null)
            {
                pJPIDParameter = new ObjectParameter("PJPID", pJPID);
            }
            else
            {
                pJPIDParameter = new ObjectParameter("PJPID", typeof(global::System.String));
            }
    
            ObjectParameter routeIDParameter;
            if (routeID != null)
            {
                routeIDParameter = new ObjectParameter("RouteID", routeID);
            }
            else
            {
                routeIDParameter = new ObjectParameter("RouteID", typeof(global::System.String));
            }
    
            ObjectParameter slsperIDParameter;
            if (slsperID != null)
            {
                slsperIDParameter = new ObjectParameter("SlsperID", slsperID);
            }
            else
            {
                slsperIDParameter = new ObjectParameter("SlsperID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<OM22200_pgSaleRouteMaster_Result>("OM22200_pgSaleRouteMaster", userIDParameter, branchIDParameter, pJPIDParameter, routeIDParameter, slsperIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="branchID">No Metadata Documentation available.</param>
        /// <param name="pJP">No Metadata Documentation available.</param>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="slsPerID">No Metadata Documentation available.</param>
        /// <param name="routeID">No Metadata Documentation available.</param>
        /// <param name="lstCustID">No Metadata Documentation available.</param>
        public ObjectResult<OM22200_pcCustomer_Result> OM22200_pcCustomer(global::System.String branchID, global::System.String pJP, global::System.String userID, global::System.String slsPerID, global::System.String routeID, global::System.String lstCustID)
        {
            ObjectParameter branchIDParameter;
            if (branchID != null)
            {
                branchIDParameter = new ObjectParameter("BranchID", branchID);
            }
            else
            {
                branchIDParameter = new ObjectParameter("BranchID", typeof(global::System.String));
            }
    
            ObjectParameter pJPParameter;
            if (pJP != null)
            {
                pJPParameter = new ObjectParameter("PJP", pJP);
            }
            else
            {
                pJPParameter = new ObjectParameter("PJP", typeof(global::System.String));
            }
    
            ObjectParameter userIDParameter;
            if (userID != null)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.String));
            }
    
            ObjectParameter slsPerIDParameter;
            if (slsPerID != null)
            {
                slsPerIDParameter = new ObjectParameter("SlsPerID", slsPerID);
            }
            else
            {
                slsPerIDParameter = new ObjectParameter("SlsPerID", typeof(global::System.String));
            }
    
            ObjectParameter routeIDParameter;
            if (routeID != null)
            {
                routeIDParameter = new ObjectParameter("RouteID", routeID);
            }
            else
            {
                routeIDParameter = new ObjectParameter("RouteID", typeof(global::System.String));
            }
    
            ObjectParameter lstCustIDParameter;
            if (lstCustID != null)
            {
                lstCustIDParameter = new ObjectParameter("LstCustID", lstCustID);
            }
            else
            {
                lstCustIDParameter = new ObjectParameter("LstCustID", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<OM22200_pcCustomer_Result>("OM22200_pcCustomer", branchIDParameter, pJPParameter, userIDParameter, slsPerIDParameter, routeIDParameter, lstCustIDParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OM22200Model", Name="OM_PJP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OM_PJP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OM_PJP object.
        /// </summary>
        /// <param name="pJPID">Initial value of the PJPID property.</param>
        /// <param name="descr">Initial value of the Descr property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        public static OM_PJP CreateOM_PJP(global::System.String pJPID, global::System.String descr, global::System.Boolean status, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp, global::System.String branchID)
        {
            OM_PJP oM_PJP = new OM_PJP();
            oM_PJP.PJPID = pJPID;
            oM_PJP.Descr = descr;
            oM_PJP.Status = status;
            oM_PJP.Crtd_DateTime = crtd_DateTime;
            oM_PJP.Crtd_Prog = crtd_Prog;
            oM_PJP.Crtd_User = crtd_User;
            oM_PJP.LUpd_DateTime = lUpd_DateTime;
            oM_PJP.LUpd_Prog = lUpd_Prog;
            oM_PJP.LUpd_User = lUpd_User;
            oM_PJP.tstamp = tstamp;
            oM_PJP.BranchID = branchID;
            return oM_PJP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PJPID
        {
            get
            {
                return _PJPID;
            }
            set
            {
                if (_PJPID != value)
                {
                    OnPJPIDChanging(value);
                    ReportPropertyChanging("PJPID");
                    _PJPID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PJPID");
                    OnPJPIDChanged();
                }
            }
        }
        private global::System.String _PJPID;
        partial void OnPJPIDChanging(global::System.String value);
        partial void OnPJPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descr
        {
            get
            {
                return _Descr;
            }
            set
            {
                OnDescrChanging(value);
                ReportPropertyChanging("Descr");
                _Descr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descr");
                OnDescrChanged();
            }
        }
        private global::System.String _Descr;
        partial void OnDescrChanging(global::System.String value);
        partial void OnDescrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Boolean _Status;
        partial void OnStatusChanging(global::System.Boolean value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                if (_BranchID != value)
                {
                    OnBranchIDChanging(value);
                    ReportPropertyChanging("BranchID");
                    _BranchID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BranchID");
                    OnBranchIDChanged();
                }
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusHandle
        {
            get
            {
                return _StatusHandle;
            }
            set
            {
                OnStatusHandleChanging(value);
                ReportPropertyChanging("StatusHandle");
                _StatusHandle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusHandle");
                OnStatusHandleChanged();
            }
        }
        private global::System.String _StatusHandle;
        partial void OnStatusHandleChanging(global::System.String value);
        partial void OnStatusHandleChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OM22200Model", Name="OM_SalesRouteMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OM_SalesRouteMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OM_SalesRouteMaster object.
        /// </summary>
        /// <param name="pJPID">Initial value of the PJPID property.</param>
        /// <param name="salesRouteID">Initial value of the SalesRouteID property.</param>
        /// <param name="custID">Initial value of the CustID property.</param>
        /// <param name="slsPerID">Initial value of the SlsPerID property.</param>
        /// <param name="slsFreq">Initial value of the SlsFreq property.</param>
        /// <param name="slsFreqType">Initial value of the SlsFreqType property.</param>
        /// <param name="visitSort">Initial value of the VisitSort property.</param>
        /// <param name="weekofVisit">Initial value of the WeekofVisit property.</param>
        /// <param name="mon">Initial value of the Mon property.</param>
        /// <param name="tue">Initial value of the Tue property.</param>
        /// <param name="wed">Initial value of the Wed property.</param>
        /// <param name="thu">Initial value of the Thu property.</param>
        /// <param name="fri">Initial value of the Fri property.</param>
        /// <param name="sat">Initial value of the Sat property.</param>
        /// <param name="sun">Initial value of the Sun property.</param>
        /// <param name="crtd_DateTime">Initial value of the Crtd_DateTime property.</param>
        /// <param name="crtd_Prog">Initial value of the Crtd_Prog property.</param>
        /// <param name="crtd_User">Initial value of the Crtd_User property.</param>
        /// <param name="lUpd_DateTime">Initial value of the LUpd_DateTime property.</param>
        /// <param name="lUpd_Prog">Initial value of the LUpd_Prog property.</param>
        /// <param name="lUpd_User">Initial value of the LUpd_User property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        public static OM_SalesRouteMaster CreateOM_SalesRouteMaster(global::System.String pJPID, global::System.String salesRouteID, global::System.String custID, global::System.String slsPerID, global::System.String slsFreq, global::System.String slsFreqType, global::System.Int32 visitSort, global::System.String weekofVisit, global::System.Boolean mon, global::System.Boolean tue, global::System.Boolean wed, global::System.Boolean thu, global::System.Boolean fri, global::System.Boolean sat, global::System.Boolean sun, global::System.DateTime crtd_DateTime, global::System.String crtd_Prog, global::System.String crtd_User, global::System.DateTime lUpd_DateTime, global::System.String lUpd_Prog, global::System.String lUpd_User, global::System.Byte[] tstamp, global::System.String branchID)
        {
            OM_SalesRouteMaster oM_SalesRouteMaster = new OM_SalesRouteMaster();
            oM_SalesRouteMaster.PJPID = pJPID;
            oM_SalesRouteMaster.SalesRouteID = salesRouteID;
            oM_SalesRouteMaster.CustID = custID;
            oM_SalesRouteMaster.SlsPerID = slsPerID;
            oM_SalesRouteMaster.SlsFreq = slsFreq;
            oM_SalesRouteMaster.SlsFreqType = slsFreqType;
            oM_SalesRouteMaster.VisitSort = visitSort;
            oM_SalesRouteMaster.WeekofVisit = weekofVisit;
            oM_SalesRouteMaster.Mon = mon;
            oM_SalesRouteMaster.Tue = tue;
            oM_SalesRouteMaster.Wed = wed;
            oM_SalesRouteMaster.Thu = thu;
            oM_SalesRouteMaster.Fri = fri;
            oM_SalesRouteMaster.Sat = sat;
            oM_SalesRouteMaster.Sun = sun;
            oM_SalesRouteMaster.Crtd_DateTime = crtd_DateTime;
            oM_SalesRouteMaster.Crtd_Prog = crtd_Prog;
            oM_SalesRouteMaster.Crtd_User = crtd_User;
            oM_SalesRouteMaster.LUpd_DateTime = lUpd_DateTime;
            oM_SalesRouteMaster.LUpd_Prog = lUpd_Prog;
            oM_SalesRouteMaster.LUpd_User = lUpd_User;
            oM_SalesRouteMaster.tstamp = tstamp;
            oM_SalesRouteMaster.BranchID = branchID;
            return oM_SalesRouteMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PJPID
        {
            get
            {
                return _PJPID;
            }
            set
            {
                if (_PJPID != value)
                {
                    OnPJPIDChanging(value);
                    ReportPropertyChanging("PJPID");
                    _PJPID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PJPID");
                    OnPJPIDChanged();
                }
            }
        }
        private global::System.String _PJPID;
        partial void OnPJPIDChanging(global::System.String value);
        partial void OnPJPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalesRouteID
        {
            get
            {
                return _SalesRouteID;
            }
            set
            {
                if (_SalesRouteID != value)
                {
                    OnSalesRouteIDChanging(value);
                    ReportPropertyChanging("SalesRouteID");
                    _SalesRouteID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SalesRouteID");
                    OnSalesRouteIDChanged();
                }
            }
        }
        private global::System.String _SalesRouteID;
        partial void OnSalesRouteIDChanging(global::System.String value);
        partial void OnSalesRouteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustID
        {
            get
            {
                return _CustID;
            }
            set
            {
                if (_CustID != value)
                {
                    OnCustIDChanging(value);
                    ReportPropertyChanging("CustID");
                    _CustID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustID");
                    OnCustIDChanged();
                }
            }
        }
        private global::System.String _CustID;
        partial void OnCustIDChanging(global::System.String value);
        partial void OnCustIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlsPerID
        {
            get
            {
                return _SlsPerID;
            }
            set
            {
                if (_SlsPerID != value)
                {
                    OnSlsPerIDChanging(value);
                    ReportPropertyChanging("SlsPerID");
                    _SlsPerID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SlsPerID");
                    OnSlsPerIDChanged();
                }
            }
        }
        private global::System.String _SlsPerID;
        partial void OnSlsPerIDChanging(global::System.String value);
        partial void OnSlsPerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlsFreq
        {
            get
            {
                return _SlsFreq;
            }
            set
            {
                OnSlsFreqChanging(value);
                ReportPropertyChanging("SlsFreq");
                _SlsFreq = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SlsFreq");
                OnSlsFreqChanged();
            }
        }
        private global::System.String _SlsFreq;
        partial void OnSlsFreqChanging(global::System.String value);
        partial void OnSlsFreqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlsFreqType
        {
            get
            {
                return _SlsFreqType;
            }
            set
            {
                OnSlsFreqTypeChanging(value);
                ReportPropertyChanging("SlsFreqType");
                _SlsFreqType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SlsFreqType");
                OnSlsFreqTypeChanged();
            }
        }
        private global::System.String _SlsFreqType;
        partial void OnSlsFreqTypeChanging(global::System.String value);
        partial void OnSlsFreqTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VisitSort
        {
            get
            {
                return _VisitSort;
            }
            set
            {
                OnVisitSortChanging(value);
                ReportPropertyChanging("VisitSort");
                _VisitSort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitSort");
                OnVisitSortChanged();
            }
        }
        private global::System.Int32 _VisitSort;
        partial void OnVisitSortChanging(global::System.Int32 value);
        partial void OnVisitSortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WeekofVisit
        {
            get
            {
                return _WeekofVisit;
            }
            set
            {
                OnWeekofVisitChanging(value);
                ReportPropertyChanging("WeekofVisit");
                _WeekofVisit = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WeekofVisit");
                OnWeekofVisitChanged();
            }
        }
        private global::System.String _WeekofVisit;
        partial void OnWeekofVisitChanging(global::System.String value);
        partial void OnWeekofVisitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Mon
        {
            get
            {
                return _Mon;
            }
            set
            {
                OnMonChanging(value);
                ReportPropertyChanging("Mon");
                _Mon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mon");
                OnMonChanged();
            }
        }
        private global::System.Boolean _Mon;
        partial void OnMonChanging(global::System.Boolean value);
        partial void OnMonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Tue
        {
            get
            {
                return _Tue;
            }
            set
            {
                OnTueChanging(value);
                ReportPropertyChanging("Tue");
                _Tue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tue");
                OnTueChanged();
            }
        }
        private global::System.Boolean _Tue;
        partial void OnTueChanging(global::System.Boolean value);
        partial void OnTueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Wed
        {
            get
            {
                return _Wed;
            }
            set
            {
                OnWedChanging(value);
                ReportPropertyChanging("Wed");
                _Wed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Wed");
                OnWedChanged();
            }
        }
        private global::System.Boolean _Wed;
        partial void OnWedChanging(global::System.Boolean value);
        partial void OnWedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Thu
        {
            get
            {
                return _Thu;
            }
            set
            {
                OnThuChanging(value);
                ReportPropertyChanging("Thu");
                _Thu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Thu");
                OnThuChanged();
            }
        }
        private global::System.Boolean _Thu;
        partial void OnThuChanging(global::System.Boolean value);
        partial void OnThuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Fri
        {
            get
            {
                return _Fri;
            }
            set
            {
                OnFriChanging(value);
                ReportPropertyChanging("Fri");
                _Fri = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fri");
                OnFriChanged();
            }
        }
        private global::System.Boolean _Fri;
        partial void OnFriChanging(global::System.Boolean value);
        partial void OnFriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sat
        {
            get
            {
                return _Sat;
            }
            set
            {
                OnSatChanging(value);
                ReportPropertyChanging("Sat");
                _Sat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sat");
                OnSatChanged();
            }
        }
        private global::System.Boolean _Sat;
        partial void OnSatChanging(global::System.Boolean value);
        partial void OnSatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sun
        {
            get
            {
                return _Sun;
            }
            set
            {
                OnSunChanging(value);
                ReportPropertyChanging("Sun");
                _Sun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sun");
                OnSunChanged();
            }
        }
        private global::System.Boolean _Sun;
        partial void OnSunChanging(global::System.Boolean value);
        partial void OnSunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Crtd_DateTime
        {
            get
            {
                return _Crtd_DateTime;
            }
            set
            {
                OnCrtd_DateTimeChanging(value);
                ReportPropertyChanging("Crtd_DateTime");
                _Crtd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Crtd_DateTime");
                OnCrtd_DateTimeChanged();
            }
        }
        private global::System.DateTime _Crtd_DateTime;
        partial void OnCrtd_DateTimeChanging(global::System.DateTime value);
        partial void OnCrtd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_Prog
        {
            get
            {
                return _Crtd_Prog;
            }
            set
            {
                OnCrtd_ProgChanging(value);
                ReportPropertyChanging("Crtd_Prog");
                _Crtd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_Prog");
                OnCrtd_ProgChanged();
            }
        }
        private global::System.String _Crtd_Prog;
        partial void OnCrtd_ProgChanging(global::System.String value);
        partial void OnCrtd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Crtd_User
        {
            get
            {
                return _Crtd_User;
            }
            set
            {
                OnCrtd_UserChanging(value);
                ReportPropertyChanging("Crtd_User");
                _Crtd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Crtd_User");
                OnCrtd_UserChanged();
            }
        }
        private global::System.String _Crtd_User;
        partial void OnCrtd_UserChanging(global::System.String value);
        partial void OnCrtd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LUpd_DateTime
        {
            get
            {
                return _LUpd_DateTime;
            }
            set
            {
                OnLUpd_DateTimeChanging(value);
                ReportPropertyChanging("LUpd_DateTime");
                _LUpd_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LUpd_DateTime");
                OnLUpd_DateTimeChanged();
            }
        }
        private global::System.DateTime _LUpd_DateTime;
        partial void OnLUpd_DateTimeChanging(global::System.DateTime value);
        partial void OnLUpd_DateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_Prog
        {
            get
            {
                return _LUpd_Prog;
            }
            set
            {
                OnLUpd_ProgChanging(value);
                ReportPropertyChanging("LUpd_Prog");
                _LUpd_Prog = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_Prog");
                OnLUpd_ProgChanged();
            }
        }
        private global::System.String _LUpd_Prog;
        partial void OnLUpd_ProgChanging(global::System.String value);
        partial void OnLUpd_ProgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUpd_User
        {
            get
            {
                return _LUpd_User;
            }
            set
            {
                OnLUpd_UserChanging(value);
                ReportPropertyChanging("LUpd_User");
                _LUpd_User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUpd_User");
                OnLUpd_UserChanged();
            }
        }
        private global::System.String _LUpd_User;
        partial void OnLUpd_UserChanging(global::System.String value);
        partial void OnLUpd_UserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                if (_BranchID != value)
                {
                    OnBranchIDChanging(value);
                    ReportPropertyChanging("BranchID");
                    _BranchID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BranchID");
                    OnBranchIDChanged();
                }
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OM22200Model", Name="OM22200_pcCustomer_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class OM22200_pcCustomer_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OM22200_pcCustomer_Result object.
        /// </summary>
        /// <param name="custId">Initial value of the CustId property.</param>
        /// <param name="custName">Initial value of the CustName property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static OM22200_pcCustomer_Result CreateOM22200_pcCustomer_Result(global::System.String custId, global::System.String custName, global::System.String status)
        {
            OM22200_pcCustomer_Result oM22200_pcCustomer_Result = new OM22200_pcCustomer_Result();
            oM22200_pcCustomer_Result.CustId = custId;
            oM22200_pcCustomer_Result.CustName = custName;
            oM22200_pcCustomer_Result.Status = status;
            return oM22200_pcCustomer_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Selected
        {
            get
            {
                return _Selected;
            }
            set
            {
                OnSelectedChanging(value);
                ReportPropertyChanging("Selected");
                _Selected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selected");
                OnSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Selected;
        partial void OnSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnSelectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustId
        {
            get
            {
                return _CustId;
            }
            set
            {
                OnCustIdChanging(value);
                ReportPropertyChanging("CustId");
                _CustId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustId");
                OnCustIdChanged();
            }
        }
        private global::System.String _CustId;
        partial void OnCustIdChanging(global::System.String value);
        partial void OnCustIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustName
        {
            get
            {
                return _CustName;
            }
            set
            {
                OnCustNameChanging(value);
                ReportPropertyChanging("CustName");
                _CustName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustName");
                OnCustNameChanged();
            }
        }
        private global::System.String _CustName;
        partial void OnCustNameChanging(global::System.String value);
        partial void OnCustNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SlsperId
        {
            get
            {
                return _SlsperId;
            }
            set
            {
                OnSlsperIdChanging(value);
                ReportPropertyChanging("SlsperId");
                _SlsperId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SlsperId");
                OnSlsperIdChanged();
            }
        }
        private global::System.String _SlsperId;
        partial void OnSlsperIdChanging(global::System.String value);
        partial void OnSlsperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr1
        {
            get
            {
                return _Addr1;
            }
            set
            {
                OnAddr1Changing(value);
                ReportPropertyChanging("Addr1");
                _Addr1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr1");
                OnAddr1Changed();
            }
        }
        private global::System.String _Addr1;
        partial void OnAddr1Changing(global::System.String value);
        partial void OnAddr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr2
        {
            get
            {
                return _Addr2;
            }
            set
            {
                OnAddr2Changing(value);
                ReportPropertyChanging("Addr2");
                _Addr2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Addr2");
                OnAddr2Changed();
            }
        }
        private global::System.String _Addr2;
        partial void OnAddr2Changing(global::System.String value);
        partial void OnAddr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PriceClassID
        {
            get
            {
                return _PriceClassID;
            }
            set
            {
                OnPriceClassIDChanging(value);
                ReportPropertyChanging("PriceClassID");
                _PriceClassID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PriceClassID");
                OnPriceClassIDChanged();
            }
        }
        private global::System.String _PriceClassID;
        partial void OnPriceClassIDChanging(global::System.String value);
        partial void OnPriceClassIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="OM22200Model", Name="OM22200_pgSaleRouteMaster_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class OM22200_pgSaleRouteMaster_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OM22200_pgSaleRouteMaster_Result object.
        /// </summary>
        /// <param name="pJPID">Initial value of the PJPID property.</param>
        /// <param name="salesRouteID">Initial value of the SalesRouteID property.</param>
        /// <param name="custID">Initial value of the CustID property.</param>
        /// <param name="slsPerID">Initial value of the SlsPerID property.</param>
        /// <param name="slsFreq">Initial value of the SlsFreq property.</param>
        /// <param name="slsFreqType">Initial value of the SlsFreqType property.</param>
        /// <param name="visitSort">Initial value of the VisitSort property.</param>
        /// <param name="weekofVisit">Initial value of the WeekofVisit property.</param>
        /// <param name="mon">Initial value of the Mon property.</param>
        /// <param name="tue">Initial value of the Tue property.</param>
        /// <param name="wed">Initial value of the Wed property.</param>
        /// <param name="thu">Initial value of the Thu property.</param>
        /// <param name="fri">Initial value of the Fri property.</param>
        /// <param name="sat">Initial value of the Sat property.</param>
        /// <param name="sun">Initial value of the Sun property.</param>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        /// <param name="tstamp">Initial value of the tstamp property.</param>
        public static OM22200_pgSaleRouteMaster_Result CreateOM22200_pgSaleRouteMaster_Result(global::System.String pJPID, global::System.String salesRouteID, global::System.String custID, global::System.String slsPerID, global::System.String slsFreq, global::System.String slsFreqType, global::System.Int32 visitSort, global::System.String weekofVisit, global::System.Boolean mon, global::System.Boolean tue, global::System.Boolean wed, global::System.Boolean thu, global::System.Boolean fri, global::System.Boolean sat, global::System.Boolean sun, global::System.String branchID, global::System.Byte[] tstamp)
        {
            OM22200_pgSaleRouteMaster_Result oM22200_pgSaleRouteMaster_Result = new OM22200_pgSaleRouteMaster_Result();
            oM22200_pgSaleRouteMaster_Result.PJPID = pJPID;
            oM22200_pgSaleRouteMaster_Result.SalesRouteID = salesRouteID;
            oM22200_pgSaleRouteMaster_Result.CustID = custID;
            oM22200_pgSaleRouteMaster_Result.SlsPerID = slsPerID;
            oM22200_pgSaleRouteMaster_Result.SlsFreq = slsFreq;
            oM22200_pgSaleRouteMaster_Result.SlsFreqType = slsFreqType;
            oM22200_pgSaleRouteMaster_Result.VisitSort = visitSort;
            oM22200_pgSaleRouteMaster_Result.WeekofVisit = weekofVisit;
            oM22200_pgSaleRouteMaster_Result.Mon = mon;
            oM22200_pgSaleRouteMaster_Result.Tue = tue;
            oM22200_pgSaleRouteMaster_Result.Wed = wed;
            oM22200_pgSaleRouteMaster_Result.Thu = thu;
            oM22200_pgSaleRouteMaster_Result.Fri = fri;
            oM22200_pgSaleRouteMaster_Result.Sat = sat;
            oM22200_pgSaleRouteMaster_Result.Sun = sun;
            oM22200_pgSaleRouteMaster_Result.BranchID = branchID;
            oM22200_pgSaleRouteMaster_Result.tstamp = tstamp;
            return oM22200_pgSaleRouteMaster_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Selected
        {
            get
            {
                return _Selected;
            }
            set
            {
                OnSelectedChanging(value);
                ReportPropertyChanging("Selected");
                _Selected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selected");
                OnSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Selected;
        partial void OnSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnSelectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PJPID
        {
            get
            {
                return _PJPID;
            }
            set
            {
                OnPJPIDChanging(value);
                ReportPropertyChanging("PJPID");
                _PJPID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PJPID");
                OnPJPIDChanged();
            }
        }
        private global::System.String _PJPID;
        partial void OnPJPIDChanging(global::System.String value);
        partial void OnPJPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalesRouteID
        {
            get
            {
                return _SalesRouteID;
            }
            set
            {
                OnSalesRouteIDChanging(value);
                ReportPropertyChanging("SalesRouteID");
                _SalesRouteID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SalesRouteID");
                OnSalesRouteIDChanged();
            }
        }
        private global::System.String _SalesRouteID;
        partial void OnSalesRouteIDChanging(global::System.String value);
        partial void OnSalesRouteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RouteName
        {
            get
            {
                return _RouteName;
            }
            set
            {
                OnRouteNameChanging(value);
                ReportPropertyChanging("RouteName");
                _RouteName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RouteName");
                OnRouteNameChanged();
            }
        }
        private global::System.String _RouteName;
        partial void OnRouteNameChanging(global::System.String value);
        partial void OnRouteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustID
        {
            get
            {
                return _CustID;
            }
            set
            {
                OnCustIDChanging(value);
                ReportPropertyChanging("CustID");
                _CustID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustID");
                OnCustIDChanged();
            }
        }
        private global::System.String _CustID;
        partial void OnCustIDChanging(global::System.String value);
        partial void OnCustIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustName
        {
            get
            {
                return _CustName;
            }
            set
            {
                OnCustNameChanging(value);
                ReportPropertyChanging("CustName");
                _CustName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustName");
                OnCustNameChanged();
            }
        }
        private global::System.String _CustName;
        partial void OnCustNameChanging(global::System.String value);
        partial void OnCustNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlsPerID
        {
            get
            {
                return _SlsPerID;
            }
            set
            {
                OnSlsPerIDChanging(value);
                ReportPropertyChanging("SlsPerID");
                _SlsPerID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SlsPerID");
                OnSlsPerIDChanged();
            }
        }
        private global::System.String _SlsPerID;
        partial void OnSlsPerIDChanging(global::System.String value);
        partial void OnSlsPerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SlsName
        {
            get
            {
                return _SlsName;
            }
            set
            {
                OnSlsNameChanging(value);
                ReportPropertyChanging("SlsName");
                _SlsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SlsName");
                OnSlsNameChanged();
            }
        }
        private global::System.String _SlsName;
        partial void OnSlsNameChanging(global::System.String value);
        partial void OnSlsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlsFreq
        {
            get
            {
                return _SlsFreq;
            }
            set
            {
                OnSlsFreqChanging(value);
                ReportPropertyChanging("SlsFreq");
                _SlsFreq = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SlsFreq");
                OnSlsFreqChanged();
            }
        }
        private global::System.String _SlsFreq;
        partial void OnSlsFreqChanging(global::System.String value);
        partial void OnSlsFreqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlsFreqType
        {
            get
            {
                return _SlsFreqType;
            }
            set
            {
                OnSlsFreqTypeChanging(value);
                ReportPropertyChanging("SlsFreqType");
                _SlsFreqType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SlsFreqType");
                OnSlsFreqTypeChanged();
            }
        }
        private global::System.String _SlsFreqType;
        partial void OnSlsFreqTypeChanging(global::System.String value);
        partial void OnSlsFreqTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VisitSort
        {
            get
            {
                return _VisitSort;
            }
            set
            {
                OnVisitSortChanging(value);
                ReportPropertyChanging("VisitSort");
                _VisitSort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitSort");
                OnVisitSortChanged();
            }
        }
        private global::System.Int32 _VisitSort;
        partial void OnVisitSortChanging(global::System.Int32 value);
        partial void OnVisitSortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WeekofVisit
        {
            get
            {
                return _WeekofVisit;
            }
            set
            {
                OnWeekofVisitChanging(value);
                ReportPropertyChanging("WeekofVisit");
                _WeekofVisit = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WeekofVisit");
                OnWeekofVisitChanged();
            }
        }
        private global::System.String _WeekofVisit;
        partial void OnWeekofVisitChanging(global::System.String value);
        partial void OnWeekofVisitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Mon
        {
            get
            {
                return _Mon;
            }
            set
            {
                OnMonChanging(value);
                ReportPropertyChanging("Mon");
                _Mon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mon");
                OnMonChanged();
            }
        }
        private global::System.Boolean _Mon;
        partial void OnMonChanging(global::System.Boolean value);
        partial void OnMonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Tue
        {
            get
            {
                return _Tue;
            }
            set
            {
                OnTueChanging(value);
                ReportPropertyChanging("Tue");
                _Tue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tue");
                OnTueChanged();
            }
        }
        private global::System.Boolean _Tue;
        partial void OnTueChanging(global::System.Boolean value);
        partial void OnTueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Wed
        {
            get
            {
                return _Wed;
            }
            set
            {
                OnWedChanging(value);
                ReportPropertyChanging("Wed");
                _Wed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Wed");
                OnWedChanged();
            }
        }
        private global::System.Boolean _Wed;
        partial void OnWedChanging(global::System.Boolean value);
        partial void OnWedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Thu
        {
            get
            {
                return _Thu;
            }
            set
            {
                OnThuChanging(value);
                ReportPropertyChanging("Thu");
                _Thu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Thu");
                OnThuChanged();
            }
        }
        private global::System.Boolean _Thu;
        partial void OnThuChanging(global::System.Boolean value);
        partial void OnThuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Fri
        {
            get
            {
                return _Fri;
            }
            set
            {
                OnFriChanging(value);
                ReportPropertyChanging("Fri");
                _Fri = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fri");
                OnFriChanged();
            }
        }
        private global::System.Boolean _Fri;
        partial void OnFriChanging(global::System.Boolean value);
        partial void OnFriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sat
        {
            get
            {
                return _Sat;
            }
            set
            {
                OnSatChanging(value);
                ReportPropertyChanging("Sat");
                _Sat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sat");
                OnSatChanged();
            }
        }
        private global::System.Boolean _Sat;
        partial void OnSatChanging(global::System.Boolean value);
        partial void OnSatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sun
        {
            get
            {
                return _Sun;
            }
            set
            {
                OnSunChanging(value);
                ReportPropertyChanging("Sun");
                _Sun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sun");
                OnSunChanged();
            }
        }
        private global::System.Boolean _Sun;
        partial void OnSunChanging(global::System.Boolean value);
        partial void OnSunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                OnBranchIDChanging(value);
                ReportPropertyChanging("BranchID");
                _BranchID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BranchID");
                OnBranchIDChanged();
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isChange
        {
            get
            {
                return _isChange;
            }
            set
            {
                OnisChangeChanging(value);
                ReportPropertyChanging("isChange");
                _isChange = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isChange");
                OnisChangeChanged();
            }
        }
        private Nullable<global::System.Boolean> _isChange;
        partial void OnisChangeChanging(Nullable<global::System.Boolean> value);
        partial void OnisChangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] tstamp
        {
            get
            {
                return StructuralObject.GetValidValue(_tstamp);
            }
            set
            {
                OntstampChanging(value);
                ReportPropertyChanging("tstamp");
                _tstamp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tstamp");
                OntstampChanged();
            }
        }
        private global::System.Byte[] _tstamp;
        partial void OntstampChanging(global::System.Byte[] value);
        partial void OntstampChanged();

        #endregion

    }

    #endregion

    
}
